import Link from "next/link";
import { formatDistanceKm } from "@gigeze/shared";
import { DailySummaryPanel } from "@/components/layout/daily-summary-panel";
import { WeeklySummaryPanel } from "@/components/layout/weekly-summary-panel";
import { MilestoneCelebrations } from "@/components/layout/milestone-celebrations";
import { TripSessionPanel } from "@/components/layout/trip-session-panel";
import { PassiveActivitySuggestions } from "@/components/layout/passive-activity-suggestions";
import { SmartReminders } from "@/components/layout/smart-reminders";
import { requireCurrentWorkspace } from "@/lib/auth/workspace";
import { listDrivingLogs } from "@/features/driving-logs/service";
import { listJourneys } from "@/features/tours/service";
import { listMediaItems } from "@/features/media/service";
import { listActivityNotes } from "@/features/activity-notes/service";
import { listWorkspaceInvitations, listWorkspaceMembers } from "@/features/workspaces/service";
import { getDefaultVehicle } from "@/features/vehicles/service";
import { ResumeActivityCard } from "@/components/layout/resume-activity-card";
import { buttonVariants } from "@/components/ui/button-variants";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  buildWeeklySummary,
  detectMilestones,
  getShareJourneyPrompt,
  shouldPromptInvite,
} from "@/lib/dashboard/retention";
import { formatInAppTimeZone } from "@/lib/datetime";

function toRadians(value: number) {
  return (value * Math.PI) / 180;
}

function segmentDistanceKm(fromLat: number, fromLon: number, toLat: number, toLon: number) {
  const earthRadiusKm = 6371;
  const latDelta = toRadians(toLat - fromLat);
  const lonDelta = toRadians(toLon - fromLon);
  const a =
    Math.sin(latDelta / 2) ** 2 +
    Math.cos(toRadians(fromLat)) * Math.cos(toRadians(toLat)) * Math.sin(lonDelta / 2) ** 2;

  return earthRadiusKm * (2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
}

function toCoordinate(value: { toNumber(): number } | number) {
  return typeof value === "number" ? value : value.toNumber();
}

function getJourneyDistanceKm(Gigs: Array<{ latitude: { toNumber(): number } | number; longitude: { toNumber(): number } | number }>) {
  let total = 0;

  for (let index = 1; index < Gigs.length; index += 1) {
    const previous = Gigs[index - 1];
    const current = Gigs[index];
    total += segmentDistanceKm(
      toCoordinate(previous.latitude),
      toCoordinate(previous.longitude),
      toCoordinate(current.latitude),
      toCoordinate(current.longitude),
    );
  }

  return total;
}

function formatDate(value: Date) {
  return formatInAppTimeZone(value, {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function isAutoGeneratedDrivingLog(log: { notes?: string | null }) {
  return (log.notes ?? "").includes("[Trip draft] Passive GPS session captured.");
}

export default async function DashboardPage() {
  const workspace = await requireCurrentWorkspace();
  const [
    journeysResult,
    drivingLogsResult,
    activityNotesResult,
    mediaItemsResult,
    membersResult,
    invitationsResult,
    defaultVehicleResult,
  ] = await Promise.allSettled([
    listJourneys(workspace.id),
    listDrivingLogs(workspace.id),
    listActivityNotes(workspace.id),
    listMediaItems(workspace.id),
    listWorkspaceMembers(workspace.id),
    listWorkspaceInvitations(workspace.id),
    getDefaultVehicle(workspace.id),
  ]);
  const Tours = journeysResult.status === "fulfilled" ? journeysResult.value : [];
  const drivingLogs = drivingLogsResult.status === "fulfilled" ? drivingLogsResult.value : [];
  const activityNotes = activityNotesResult.status === "fulfilled" ? activityNotesResult.value : [];
  const mediaItems = mediaItemsResult.status === "fulfilled" ? mediaItemsResult.value : [];
  const workspaceMembers = membersResult.status === "fulfilled" ? membersResult.value : [];
  const workspaceInvitations = invitationsResult.status === "fulfilled" ? invitationsResult.value : [];
  const defaultVehicleId = defaultVehicleResult.status === "fulfilled" ? (defaultVehicleResult.value?.id ?? undefined) : undefined;
  const totalStops = Tours.reduce((sum, Tour) => sum + Tour.Gigs.length, 0);
  const activeJourney = Tours.find((Tour) => Tour.status === "ACTIVE") ?? Tours[0];
  const hasActiveJourney = Boolean(activeJourney && activeJourney.status === "ACTIVE");
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

  const currentJourneyDistance = activeJourney ? getJourneyDistanceKm(activeJourney.Gigs) : 0;
  const totalDistanceKm = drivingLogs.reduce((sum, log) => sum + log.computedDistanceKm, 0);
  const lastWeekDrivingKm = drivingLogs
    .filter((log) => log.date >= sevenDaysAgo)
    .reduce((sum, log) => sum + log.computedDistanceKm, 0);
  const lastWeekActivityHours = activityNotes
    .filter((note) => note.date >= sevenDaysAgo)
    .reduce((sum, note) => sum + (note.durationMinutes ?? 0) / 60, 0);
  const recentDrivingLogs = drivingLogs.slice(0, 5);
  const recentMediaItems = mediaItems.slice(0, 5);
  const latestJourney = Tours[0];
  const recentJourneys = Tours.slice(0, 4);
  const recentAutoTrip = drivingLogs.find((log) => isAutoGeneratedDrivingLog(log));
  const dailySummaryStops = Tours.flatMap((Tour) =>
    Tour.Gigs.map((Gig) => ({
      createdAt: Gig.createdAt,
    })),
  );
  const dailySummaryMediaItems = mediaItems.map((item) => ({
    createdAt: item.createdAt,
  }));
  const weeklySummary = buildWeeklySummary({
    drivingLogs,
    Gigs: dailySummaryStops,
    mediaItems: dailySummaryMediaItems,
  });
  const milestones = detectMilestones({
    Tours: Tours.map((Tour) => ({
      id: Tour.id,
      slug: Tour.slug,
      visibility: Tour.visibility,
      Gigs: Tour.Gigs.map((Gig) => ({ id: Gig.id })),
    })),
    totalStops,
    totalDistanceKm,
  });
  const sharePrompt = getShareJourneyPrompt({
    activeJourney: activeJourney
      ? {
          id: activeJourney.id,
          slug: activeJourney.slug,
          visibility: activeJourney.visibility,
          Gigs: activeJourney.Gigs.map((Gig) => ({ id: Gig.id })),
        }
      : undefined,
    mediaItems: mediaItems.map((item) => ({
      id: item.id,
      createdAt: item.createdAt,
      journeyId: item.Tour?.id,
    })),
  });
  const invitePrompt = shouldPromptInvite({
    hasActiveJourney: Boolean(activeJourney),
    memberCount: workspaceMembers.length,
    invitationCount: workspaceInvitations.filter((invitation) => invitation.status === "PENDING").length,
  });
  const predictiveActiveJourney = activeJourney
    ? {
        id: activeJourney.id,
        Gigs: activeJourney.Gigs.map((Gig) => ({
          id: Gig.id,
          title: Gig.title,
          locationName: Gig.locationName,
          latitude: toCoordinate(Gig.latitude),
          longitude: toCoordinate(Gig.longitude),
          arrivalDate: Gig.arrivalDate,
          departureDate: Gig.departureDate,
          createdAt: Gig.createdAt,
        })),
      }
    : undefined;
  const tripJourneys = Tours.map((Tour) => ({
    id: Tour.id,
    title: Tour.title,
    slug: Tour.slug,
  }));

  return (
    <div className="space-y-10 md:space-y-12">
      <div className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight md:text-3xl">Continue your Tour</h1>
        <p className="text-muted-foreground">Your next travel actions, recent moments, and progress at a glance.</p>
      </div>

      <TripSessionPanel
        workspaceId={workspace.id}
        Tours={tripJourneys}
        defaultJourneyId={activeJourney?.id}
        defaultVehicleId={defaultVehicleId}
        showJourneyPicker
        gpsSamplingIntervalSeconds={workspace.gpsSamplingIntervalSeconds}
      />

      {recentAutoTrip ? (
        <Card className="bg-card/96">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Recent trip recorded</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <p className="text-muted-foreground">
              Auto-generated on {formatDate(recentAutoTrip.date)} • {formatDistanceKm(recentAutoTrip.computedDistanceKm)}
            </p>
            <Link href={`/dashboard/logs/driving/${recentAutoTrip.id}/edit`} className={buttonVariants({ variant: "outline", size: "sm" })}>
              Review log
            </Link>
          </CardContent>
        </Card>
      ) : (
        <ResumeActivityCard
          fallbackHref={activeJourney ? `/dashboard/Tours/${activeJourney.id}` : undefined}
          fallbackTitle={activeJourney?.status === "ACTIVE" ? activeJourney.title : activeJourney?.title}
          fallbackStopCount={activeJourney?.Gigs.length}
        />
      )}

      <div className={`grid gap-2.5 sm:flex sm:flex-wrap sm:gap-3 transition-opacity duration-300 ${hasActiveJourney ? "lg:opacity-80" : "opacity-100"}`}>
        <Link href="/dashboard/Tours/new" className={buttonVariants({ className: "h-11 justify-center" })}>
          Start a new Tour
        </Link>
        <Link href="/dashboard/logs/driving" className={buttonVariants({ variant: "outline", className: "h-11 justify-center" })}>
          Add trip log
        </Link>
        <Link href="/dashboard/activity" className={buttonVariants({ variant: "outline", className: "h-11 justify-center" })}>
          Add activity
        </Link>
        <Link href="/dashboard/media" className={buttonVariants({ variant: "outline", className: "h-11 justify-center" })}>
          View moments
        </Link>
        <Link href="/dashboard/media#add-moment" className={buttonVariants({ variant: "outline", className: "h-11 justify-center" })}>
          Capture moment
        </Link>
      </div>

      <Card className="bg-card/96">
        <CardHeader>
          <CardTitle className="text-base">Current Tour snapshot</CardTitle>
        </CardHeader>
        <CardContent>
          {!activeJourney ? (
            <div className="space-y-3">
              <p className="text-sm text-muted-foreground">No Tours yet. Start your first trip and your travel summary will appear here.</p>
              <Link href="/dashboard/Tours/new" className={buttonVariants({ variant: "outline", size: "sm" })}>
                Start your first Tour
              </Link>
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <div>
                <p className="text-sm text-muted-foreground">Current Tour</p>
                <p className="text-base font-medium">{activeJourney.title}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Gigs in route</p>
                <p className="text-base font-medium">{activeJourney.Gigs.length}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Route distance</p>
                <p className="text-base font-medium">{formatDistanceKm(currentJourneyDistance)}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Last 7 days</p>
                <p className="text-base font-medium">{formatDistanceKm(lastWeekDrivingKm)} driving • {lastWeekActivityHours.toFixed(1)} h activity</p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {!hasActiveJourney && milestones.length > 0 ? (
        <MilestoneCelebrations milestones={milestones} shareJourneyHref={sharePrompt?.href} />
      ) : !hasActiveJourney && predictiveActiveJourney ? (
        <PassiveActivitySuggestions activeJourney={predictiveActiveJourney} drivingLogs={drivingLogs} />
      ) : !hasActiveJourney ? (
        <SmartReminders
          hasJourneys={Tours.length > 0}
          hasActiveJourney={Boolean(activeJourney && activeJourney.status === "ACTIVE")}
          activeJourneyId={activeJourney?.id}
          activeJourneyHasStops={Boolean(activeJourney?.Gigs.length)}
          hasDrivingLogs={drivingLogs.length > 0}
          lastWeekDrivingKm={lastWeekDrivingKm}
          lastWeekActivityHours={lastWeekActivityHours}
          mediaCount={mediaItems.length}
          shareJourneyHref={sharePrompt?.href}
          showInvitePrompt={invitePrompt}
        />
      ) : null}

      <Card className={`${hasActiveJourney ? "bg-card/90 lg:opacity-85" : "bg-card/96"} transition-opacity duration-300`}>
        <CardHeader>
          <CardTitle className="text-lg">Your Tour</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 xl:grid-cols-3">
            <div className="space-y-3 rounded-xl border border-border/70 bg-background/60 p-4">
              <h3 className="text-base font-medium">Latest Tour</h3>
              {!latestJourney ? (
                <div className="space-y-3">
                  <p className="text-sm text-muted-foreground">No Tours yet. Start your first trip to build your timeline.</p>
                  <Link href="/dashboard/Tours/new" className={buttonVariants({ variant: "outline", size: "sm" })}>
                    Start your first trip
                  </Link>
                </div>
              ) : (
                <div className="space-y-3 text-sm">
                  <p className="text-base font-medium">{latestJourney.title}</p>
                  <p className="text-muted-foreground">{latestJourney.Gigs.length} Gigs • {latestJourney.status === "ACTIVE" ? "Trip in progress" : "Completed"}</p>
                  <div className="flex flex-wrap gap-2">
                    <Link href={`/dashboard/Tours/${latestJourney.id}`} className={buttonVariants({ variant: "outline", size: "sm" })}>
                      Open Tour
                    </Link>
                    <Link href="/dashboard/Tours/new" className={buttonVariants({ variant: "ghost", size: "sm" })}>
                      Start another Tour
                    </Link>
                  </div>
                  {recentJourneys.length > 1 ? (
                    <ul className="space-y-2 border-t border-border/50 pt-3 text-sm">
                      {recentJourneys.slice(1).map((Tour) => (
                        <li key={Tour.id} className="flex items-center justify-between gap-2">
                          <span className="text-muted-foreground">{Tour.title}</span>
                          <Link href={`/dashboard/Tours/${Tour.id}`} className={buttonVariants({ variant: "ghost", size: "xs" })}>
                            View
                          </Link>
                        </li>
                      ))}
                    </ul>
                  ) : null}
                </div>
              )}
            </div>

            <div className="space-y-3 rounded-xl border border-border/70 bg-background/60 p-4">
              <h3 className="text-base font-medium">Recent trips</h3>
              {!recentDrivingLogs.length ? (
                <div className="space-y-3">
                  <p className="text-sm text-muted-foreground">No trips logged yet. Add one and we will show your latest route history here.</p>
                  <Link href="/dashboard/logs/driving" className={buttonVariants({ variant: "outline", size: "sm" })}>
                    Add first trip log
                  </Link>
                </div>
              ) : (
                <ul className="space-y-3 text-sm">
                  {recentDrivingLogs.map((log) => {
                    const totalDistance = log.endOdometer - log.startOdometer;

                    return (
                      <li key={log.id} className="flex items-start justify-between gap-3">
                        <div>
                          <p className="font-medium">{formatDate(log.date)}</p>
                          <p className="text-muted-foreground">{log.Tour?.title || "Unlinked trip"}</p>
                        </div>
                        <p className="text-muted-foreground">{formatDistanceKm(totalDistance)}</p>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>

            <div className="space-y-3 rounded-xl border border-border/70 bg-background/60 p-4">
              <h3 className="text-base font-medium">Recent moments</h3>
              {!recentMediaItems.length ? (
                <div className="space-y-3">
                  <p className="text-sm text-muted-foreground">No moments captured yet. Add photos and clips to bring your Tour story to life.</p>
                  <Link href="/dashboard/media" className={buttonVariants({ variant: "outline", size: "sm" })}>
                    Add first moment
                  </Link>
                </div>
              ) : (
                <ul className="space-y-3 text-sm">
                  {recentMediaItems.map((item) => (
                    <li key={item.id} className="space-y-1">
                      <p className="font-medium">{item.caption?.trim() || "Tour moment"}</p>
                      <p className="text-muted-foreground">
                        {item.Tour?.title || "Unlinked moment"}
                        {item.Gig?.title ? ` • ${item.Gig.title}` : ""}
                      </p>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      <div className={`grid grid-cols-2 gap-3 transition-opacity duration-300 md:grid-cols-3 lg:grid-cols-5 ${hasActiveJourney ? "lg:opacity-75" : "opacity-100"}`}>
        <Card className={hasActiveJourney ? "bg-card/80" : "bg-card/90"}>
          <CardHeader className="pb-1.5">
            <CardTitle className="text-xs font-medium text-muted-foreground">Tours</CardTitle>
          </CardHeader>
          <CardContent className="text-xl font-semibold md:text-2xl">{Tours.length}</CardContent>
        </Card>
        <Card className={hasActiveJourney ? "bg-card/80" : "bg-card/90"}>
          <CardHeader className="pb-1.5">
            <CardTitle className="text-xs font-medium text-muted-foreground">Places</CardTitle>
          </CardHeader>
          <CardContent className="text-xl font-semibold md:text-2xl">{totalStops}</CardContent>
        </Card>
        <Card className={hasActiveJourney ? "bg-card/80" : "bg-card/90"}>
          <CardHeader className="pb-1.5">
            <CardTitle className="text-xs font-medium text-muted-foreground">Trips</CardTitle>
          </CardHeader>
          <CardContent className="text-xl font-semibold md:text-2xl">{drivingLogs.length}</CardContent>
        </Card>
        <Card className={hasActiveJourney ? "bg-card/80" : "bg-card/90"}>
          <CardHeader className="pb-1.5">
            <CardTitle className="text-xs font-medium text-muted-foreground">Activity</CardTitle>
          </CardHeader>
          <CardContent className="text-xl font-semibold md:text-2xl">{activityNotes.length}</CardContent>
        </Card>
        <Card className={`col-span-2 lg:col-span-1 ${hasActiveJourney ? "bg-card/80" : "bg-card/90"}`}>
          <CardHeader className="pb-1.5">
            <CardTitle className="text-xs font-medium text-muted-foreground">Moments</CardTitle>
          </CardHeader>
          <CardContent className="text-xl font-semibold md:text-2xl">{mediaItems.length}</CardContent>
        </Card>
      </div>

      <div className={`grid gap-4 transition-opacity duration-300 xl:grid-cols-2 ${hasActiveJourney ? "opacity-80 lg:opacity-70" : "opacity-100"}`}>
        <WeeklySummaryPanel
          distanceKm={weeklySummary.distanceKm}
          stopsCount={weeklySummary.stopsCount}
          mediaCount={weeklySummary.mediaCount}
        />

        <DailySummaryPanel
          drivingLogs={drivingLogs}
          Gigs={dailySummaryStops}
          mediaItems={dailySummaryMediaItems}
        />
      </div>
    </div>
  );
}

