import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";

const {
  mockRequireCurrentWorkspace,
  mockListJourneys,
  mockListDrivingLogsPage,
  mockListVehicles,
  mockGetLatestOdometerForVehicle,
} = vi.hoisted(() => ({
  mockRequireCurrentWorkspace: vi.fn(),
  mockListJourneys: vi.fn(),
  mockListDrivingLogsPage: vi.fn(),
  mockListVehicles: vi.fn(),
  mockGetLatestOdometerForVehicle: vi.fn(),
}));

vi.mock("@/lib/auth/workspace", () => ({
  requireCurrentWorkspace: mockRequireCurrentWorkspace,
}));

vi.mock("@/features/tours/service", () => ({
  listJourneys: mockListJourneys,
}));

vi.mock("@/features/driving-logs/service", () => ({
  listDrivingLogsPage: mockListDrivingLogsPage,
}));

vi.mock("@/features/vehicles/service", () => ({
  listVehicles: mockListVehicles,
  getLatestOdometerForVehicle: mockGetLatestOdometerForVehicle,
}));

vi.mock("@/features/driving-logs/actions", () => ({
  createDrivingLogAction: vi.fn(),
  deleteDrivingLogAction: vi.fn(),
}));

vi.mock("next/link", () => ({
  default: ({ href, children, className }: { href: string; children: ReactNode; className?: string }) => (
    <a href={href} className={className}>
      {children}
    </a>
  ),
}));

vi.mock("@/components/forms/action-submit-button", () => ({
  ActionSubmitButton: ({ label }: { label: string }) => <button type="submit">{label}</button>,
}));

vi.mock("@/components/forms/confirm-submit-button", () => ({
  ConfirmSubmitButton: ({ triggerLabel }: { triggerLabel: string }) => <button type="button">{triggerLabel}</button>,
}));

vi.mock("@/components/forms/vehicle-odometer-fields", () => ({
  VehicleOdometerFields: () => <div>Vehicle odometer fields</div>,
}));

vi.mock("@/components/driving-logs/expandable-trip-logs-table", () => ({
  ExpandableTripLogsTable: ({ rows }: { rows: Array<{ dateText: string; totalText: string }> }) => (
    <div>
      Expandable trip logs table
      {rows.map((row) => (
        <span key={`${row.dateText}-${row.totalText}`}>
          {row.dateText} {row.totalText}
        </span>
      ))}
    </div>
  ),
}));

import DrivingLogsPage from "@/app/(app)/dashboard/logs/driving/page";

describe("dashboard driving page smoke", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequireCurrentWorkspace.mockResolvedValue({ id: "workspace-1" });
    mockListJourneys.mockResolvedValue([{ id: "Tour-1", title: "Tasmania Loop", status: "ACTIVE" }]);
    mockListVehicles.mockResolvedValue([{ id: "vehicle-1", name: "Tassie Cruiser", isDefault: true }]);
    mockGetLatestOdometerForVehicle.mockResolvedValue(12345);
  });

  it("passes date and source filters to the paginated query and preserves them in pagination links", async () => {
    mockListDrivingLogsPage.mockResolvedValue({
      logs: [
        {
          id: "log-1",
          date: new Date("2026-04-08T00:00:00.000Z"),
          startTime: new Date("2026-04-08T05:15:00.000Z"),
          endTime: new Date("2026-04-08T06:45:00.000Z"),
          startOdometer: 1000,
          endOdometer: 1125,
          businessKm: 100,
          personalKm: 25,
          notes: "[Trip draft] Passive GPS session captured.",
          startLocation: "Hobart",
          endLocation: "Richmond",
          Tour: { id: "Tour-1", title: "Tasmania Loop", slug: "tasmania-loop" },
          vehicle: { id: "vehicle-1", name: "Tassie Cruiser" },
        },
      ],
      totalCount: 11,
    });

    const element = await DrivingLogsPage({
      searchParams: Promise.resolve({
        from: "2026-04-01",
        to: "2026-04-30",
        vehicleId: "vehicle-1",
        journeyId: "Tour-1",
        source: "auto",
        page: "2",
      }),
    });
    const html = renderToStaticMarkup(element);

    expect(mockListDrivingLogsPage).toHaveBeenCalledWith(
      "workspace-1",
      2,
      10,
      expect.objectContaining({
        vehicleId: "vehicle-1",
        journeyId: "Tour-1",
        autoGeneratedOnly: true,
      }),
    );

    const calledFilters = mockListDrivingLogsPage.mock.calls[0]?.[3] as { from: Date; to: Date };
    expect(calledFilters.from.toISOString()).toBe("2026-03-31T13:00:00.000Z");
    expect(calledFilters.to.toISOString()).toBe("2026-04-30T13:59:59.999Z");
    expect(html).toContain("Page 2 of 2");
    expect(html).toContain("/dashboard/logs/driving?from=2026-04-01&amp;to=2026-04-30&amp;journeyId=Tour-1&amp;vehicleId=vehicle-1&amp;source=auto");
    expect(html).toContain("Auto-generated");
  });

  it("shows the filtered empty state when no logs match", async () => {
    mockListDrivingLogsPage.mockResolvedValue({ logs: [], totalCount: 0 });

    const element = await DrivingLogsPage({
      searchParams: Promise.resolve({ from: "2026-04-01", source: "auto" }),
    });
    const html = renderToStaticMarkup(element);

    expect(html).toContain("No trip logs match these filters");
    expect(html).toContain("Try clearing one or more filters to widen the results.");
    expect(html).toContain("Reset");
  });

  it("renders mobile synced trip timestamps in Sydney local time", async () => {
    mockListDrivingLogsPage.mockResolvedValue({
      logs: [
        {
          id: "log-1",
          date: new Date("2026-04-20T20:43:00.000Z"),
          startTime: new Date("2026-04-20T20:43:00.000Z"),
          endTime: new Date("2026-04-20T20:45:00.000Z"),
          startOdometer: 83807,
          endOdometer: 83807,
          businessKm: 0,
          personalKm: 0,
          notes: "[Trip draft] Passive GPS session captured.",
          startLocation: "GPS trip start",
          endLocation: "GPS trip end",
          Tour: null,
          vehicle: { id: "vehicle-1", name: "Tassie Cruiser" },
        },
      ],
      totalCount: 1,
    });

    const element = await DrivingLogsPage({
      searchParams: Promise.resolve({}),
    });
    const html = renderToStaticMarkup(element);

    expect(html).toContain("21 Apr 2026");
    expect(html).toContain("06:43 am - 06:45 am");
    expect(html).toContain("startFormattedAddress");
    expect(html).toContain("endFormattedAddress");
    expect(html).toContain("Use suburb/state or a recognisable place name.");
  });
});
