import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";

const {
  mockRequireCurrentWorkspace,
  mockListVehicles,
  mockListJourneys,
  mockListDrivingLogsForExport,
} = vi.hoisted(() => ({
  mockRequireCurrentWorkspace: vi.fn(),
  mockListVehicles: vi.fn(),
  mockListJourneys: vi.fn(),
  mockListDrivingLogsForExport: vi.fn(),
}));

vi.mock("@/lib/auth/workspace", () => ({
  requireCurrentWorkspace: mockRequireCurrentWorkspace,
}));

vi.mock("@/features/vehicles/service", () => ({
  listVehicles: mockListVehicles,
}));

vi.mock("@/features/tours/service", () => ({
  listJourneys: mockListJourneys,
}));

vi.mock("@/features/driving-logs/service", () => ({
  listDrivingLogsForExport: mockListDrivingLogsForExport,
}));

vi.mock("next/link", () => ({
  default: ({ href, children, className }: { href: string; children: ReactNode; className?: string }) => (
    <a href={href} className={className}>
      {children}
    </a>
  ),
}));

import DrivingLogExportPage from "@/app/(app)/dashboard/logs/driving/export/page";

describe("dashboard driving export page smoke", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequireCurrentWorkspace.mockResolvedValue({ id: "workspace-1", name: "Matts tour workspace" });
    mockListVehicles.mockResolvedValue([{ id: "vehicle-1", name: "Tassie Cruiser", registration: "TAS-123", isDefault: true }]);
    mockListJourneys.mockResolvedValue([{ id: "Tour-1", title: "Tasmania Loop" }]);
  });

  it("does not fetch preview rows when no filters are provided", async () => {
    const element = await DrivingLogExportPage({ searchParams: Promise.resolve({}) });
    const html = renderToStaticMarkup(element);

    expect(mockListDrivingLogsForExport).not.toHaveBeenCalled();
    expect(html).toContain("ATO-style driving log export");
    expect(html).toContain("Confirm details with your accountant.");
    expect(html).not.toContain("Download CSV");
  });

  it("shows preview and validation warning for inconsistent entries", async () => {
    mockListDrivingLogsForExport.mockResolvedValue([
      {
        id: "log-1",
        date: new Date("2026-04-07T00:00:00.000Z"),
        startOdometer: 500,
        endOdometer: 600,
        businessKm: 50,
        personalKm: 25,
        startLocation: "",
        endLocation: null,
        notes: null,
        vehicle: { id: "vehicle-1", name: "Tassie Cruiser" },
        Tour: { id: "Tour-1", title: "Tasmania Loop" },
        gpsSamples: [],
      },
    ]);

    const element = await DrivingLogExportPage({
      searchParams: Promise.resolve({
        from: "2026-04-01",
        to: "2026-04-30",
        vehicleId: "vehicle-1",
        journeyId: "Tour-1",
        source: "auto",
      }),
    });
    const html = renderToStaticMarkup(element);

    expect(mockListDrivingLogsForExport).toHaveBeenCalledWith(
      "workspace-1",
      expect.objectContaining({ vehicleId: "vehicle-1", journeyId: "Tour-1", autoGeneratedOnly: true }),
    );
    expect(html).toContain("Preview (1 entries)");
    expect(html).toContain("Some entries need review before export");
    expect(html).toContain("Business use %");
    expect(html).toContain("ATO-style logbook period summary");
    expect(html).toContain("Total days");
    expect(html).toContain("GPS evidence count");
    expect(html).toContain("ATO logbooks are commonly based on a continuous 12-week representative period.");
    expect(html).toContain("Matts tour workspace");
    expect(html).toContain("Missing locations");
    expect(html).toContain("Review before export");
    expect(html).toContain("Download CSV");
    expect(html).toContain("/api/logs/driving/export?from=2026-04-01&amp;to=2026-04-30&amp;vehicleId=vehicle-1&amp;journeyId=Tour-1&amp;source=auto");
  });
});
