import { NextResponse } from "next/server";
import { buildDrivingLogExportRow, buildDrivingLogExportSummaryRows, drivingLogExportHeader } from "@/features/driving-logs/export";
import { listDrivingLogsForExport } from "@/features/driving-logs/service";
import { requireWorkspaceOwner } from "@/lib/auth/workspace";
import { formatDateInputValue, parseAppDateEnd, parseAppDateStart } from "@/lib/datetime";
import { getErrorMessage } from "@/lib/utils/app-error";

function parseDateStart(value: string | null) {
  return parseAppDateStart(value);
}

function parseDateEnd(value: string | null) {
  return parseAppDateEnd(value);
}

function escapeCsv(value: string | number) {
  const raw = String(value);
  if (/[,"\n]/.test(raw)) {
    return `"${raw.replace(/"/g, '""')}"`;
  }

  return raw;
}

function formatDate(value: Date) {
  return formatDateInputValue(value);
}

export async function GET(request: Request) {
  const workspace = await requireWorkspaceOwner();

  try {
    const url = new URL(request.url);
    const from = parseDateStart(url.searchParams.get("from"));
    const to = parseDateEnd(url.searchParams.get("to"));
    const vehicleId = url.searchParams.get("vehicleId") || undefined;
    const journeyId = url.searchParams.get("journeyId") || undefined;
    const autoGeneratedOnly = url.searchParams.get("source") === "auto";

    const logs = await listDrivingLogsForExport(workspace.id, {
      from,
      to,
      vehicleId,
      journeyId,
      autoGeneratedOnly,
    });

    const rows = logs.map(buildDrivingLogExportRow);
    const summaryRows = buildDrivingLogExportSummaryRows(logs, {
      periodStart: from,
      periodEnd: to,
      workspaceName: workspace.name,
    });

    const csv = [...summaryRows, drivingLogExportHeader, ...rows]
      .map((row) => row.map((cell) => escapeCsv(cell)).join(","))
      .join("\n");

    const filenameParts = [
      "driving-log",
      from ? formatDate(from) : "all",
      to ? formatDate(to) : "latest",
    ];

    return new NextResponse(csv, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename=\"${filenameParts.join("-")}.csv\"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: getErrorMessage(error) }, { status: 400 });
  }
}
