import { beforeEach, describe, expect, it, vi } from "vitest";

const { mockRequireWorkspaceOwner, mockListDrivingLogsForExport } = vi.hoisted(() => ({
  mockRequireWorkspaceOwner: vi.fn(),
  mockListDrivingLogsForExport: vi.fn(),
}));

vi.mock("@/lib/auth/workspace", () => ({
  requireWorkspaceOwner: mockRequireWorkspaceOwner,
}));

vi.mock("@/features/driving-logs/service", () => ({
  listDrivingLogsForExport: mockListDrivingLogsForExport,
}));

import { GET } from "@/app/api/logs/driving/export/route";

describe("driving log export route", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequireWorkspaceOwner.mockResolvedValue({ id: "workspace-1", name: "Matts tour workspace" });
  });

  it("returns csv with filters and escaped values", async () => {
    mockListDrivingLogsForExport.mockResolvedValue([
      {
        id: "log-1",
        date: new Date("2026-04-08T05:00:00.000Z"),
        startTime: new Date("2026-04-08T05:15:00.000Z"),
        endTime: new Date("2026-04-08T06:45:00.000Z"),
        startOdometer: 1000,
        endOdometer: 1125,
        businessKm: 100,
        personalKm: 25,
        startLocation: "Hobart",
        endLocation: "Launceston",
        purpose: "Client meeting",
        notes: "Fuel, tolls \"paid\"\n[Trip draft] Passive GPS session captured. Mode: DRIVE. Estimated distance 125 km. Route samples: 7.",
        vehicle: { id: "vehicle-1", name: "Tassie Cruiser", registration: "TAS-123" },
        Tour: { id: "Tour-1", title: "Tasmania Loop" },
        gpsSamples: [{ id: "sample-1" }],
      },
    ]);

    const response = await GET(
      new Request(
        "http://localhost/api/logs/driving/export?from=2026-04-01&to=2026-04-30&vehicleId=vehicle-1&journeyId=Tour-1&source=auto",
      ),
    );

    expect(response.status).toBe(200);
    expect(mockListDrivingLogsForExport).toHaveBeenCalledWith(
      "workspace-1",
      expect.objectContaining({
        vehicleId: "vehicle-1",
        journeyId: "Tour-1",
        autoGeneratedOnly: true,
      }),
    );

    const calledFilters = mockListDrivingLogsForExport.mock.calls[0]?.[1] as { from: Date; to: Date };
    expect(calledFilters.from.toISOString()).toBe("2026-03-31T13:00:00.000Z");
    expect(calledFilters.to.toISOString()).toBe("2026-04-30T13:59:59.999Z");

    expect(response.headers.get("Content-Type")).toContain("text/csv");
    expect(response.headers.get("Content-Disposition")).toContain(
      'attachment; filename="driving-log-2026-04-01-2026-04-30.csv"',
    );

    const csv = await response.text();
    expect(csv).toContain("ATO-style driving log period summary");
    expect(csv).toContain("Workspace,Matts tour workspace");
    expect(csv).toContain("Period start,2026-04-01");
    expect(csv).toContain("Period end,2026-04-30");
    expect(csv).toContain("Total days,30");
    expect(csv).toContain("GPS evidence count,1");
    expect(csv).toContain("Vehicles included,Tassie Cruiser (TAS-123)");
    expect(csv).toContain("Date,Start Time,End Time,Vehicle,Registration,Tour,Start Location,End Location,Start Odometer,End Odometer,Distance Travelled,Business KM,Personal KM,Use Type,Purpose,Notes");
    expect(csv).toContain('2026-04-08,15:15,16:45,Tassie Cruiser,TAS-123,Tasmania Loop,Hobart,Launceston,1000,1125,125,100,25,Mixed,Client meeting,"Fuel, tolls ""paid""; GPS route evidence captured"');
    expect(csv).not.toContain("Passive GPS session captured");
    expect(csv).not.toContain("Route samples");
  });

  it("exports blank optional fields without failing", async () => {
    mockListDrivingLogsForExport.mockResolvedValue([
      {
        id: "log-1",
        date: new Date("2026-04-08T05:00:00.000Z"),
        startTime: null,
        endTime: null,
        startOdometer: 0,
        endOdometer: 0,
        businessKm: 0,
        personalKm: 0,
        notes: null,
        vehicle: null,
        Tour: null,
        gpsSamples: [],
      },
    ]);

    const response = await GET(new Request("http://localhost/api/logs/driving/export"));
    const csv = await response.text();

    expect(response.status).toBe(200);
    expect(csv).toContain("2026-04-08,,,,,,,,0,0,0,0,0,,,");
  });

  it("returns 400 json when export fails", async () => {
    mockListDrivingLogsForExport.mockRejectedValue(new Error("export-failed"));

    const response = await GET(new Request("http://localhost/api/logs/driving/export"));
    const body = (await response.json()) as { error: string };

    expect(response.status).toBe(400);
    expect(body.error).toBe("export-failed");
  });
});
