import type { TripMode, VehicleMode } from "@gigeze/shared";
import { calculateTripDistanceKm } from "@/features/trips/tracking";
import { prisma } from "@/lib/db/prisma";
import { reverseGeocodeTripEndpoints } from "@/lib/maps/geocoding";
import { type DrivingLogCreateInput } from "@/lib/validation";
import { AppError } from "@/lib/utils/app-error";

export type DrivingLogExportFilters = {
  from?: Date;
  to?: Date;
  vehicleId?: string;
  journeyId?: string;
  autoGeneratedOnly?: boolean;
};

export type DrivingLogListFilters = {
  from?: Date;
  to?: Date;
  vehicleId?: string;
  journeyId?: string;
  autoGeneratedOnly?: boolean;
};

export type DrivingLogListPage = {
  logs: Awaited<ReturnType<typeof listDrivingLogs>>;
  totalCount: number;
};

export type DrivingLogServiceContext = {
  workspaceId: string;
  userId: string;
};

export type DeletedDrivingLog = {
  id: string;
  deletedAt: Date;
  updatedAt: Date;
};

export type MobileDrivingLogSummary = {
  id: string;
  journeyId: string | null;
  journeyTitle: string | null;
  tripMode: TripMode;
  vehicleId: string | null;
  vehicleName: string | null;
  date: Date;
  startedAt: Date | null;
  endedAt: Date | null;
  startOdometer: number;
  endOdometer: number;
  businessKm: number;
  personalKm: number;
  purpose: string | null;
  startLocation: string | null;
  endLocation: string | null;
  computedDistanceKm: number;
  updatedAt: Date;
};

export type DrivingLogGpsSampleInput = {
  latitude: number;
  longitude: number;
  accuracyMeters: number | null;
  recordedAt: Date;
};

export type DrivingLogRoutePreview = {
  id: string;
  date: Date;
  startTime: Date | null;
  endTime: Date | null;
  startLocation: string | null;
  endLocation: string | null;
  startOdometer: number;
  endOdometer: number;
  businessKm: number;
  personalKm: number;
  purpose: string | null;
  vehicle: { id: string; name: string } | null;
  Tour: { id: string; title: string; slug: string } | null;
  computedDistanceKm: number;
  samples: Array<{
    id: string;
    latitude: number;
    longitude: number;
    accuracyMeters: number | null;
    recordedAt: Date;
  }>;
};

type DrivingLogDistanceSource = {
  startOdometer: number;
  endOdometer: number;
  businessKm: number;
  personalKm: number;
  purpose?: string | null;
  gpsSamples?: Array<{
    latitude: number | { toNumber(): number };
    longitude: number | { toNumber(): number };
    recordedAt?: Date;
  }>;
};

function toCoordinateNumber(value: number | { toNumber(): number }) {
  return typeof value === "number" ? value : value.toNumber();
}

const weakGpsLocationLabels = new Set([
  "gps route recorded",
  "gps trip start",
  "gps trip end",
  "unknown start",
  "unknown end",
]);

function isWeakGpsLocationLabel(value?: string | null) {
  const normalized = value?.trim().toLowerCase();
  return !normalized || weakGpsLocationLabels.has(normalized);
}

export function getDrivingLogComputedDistanceKm(log: DrivingLogDistanceSource) {
  const odometerDistanceKm = Math.max(0, log.endOdometer - log.startOdometer);
  const splitDistanceKm = Math.max(0, log.businessKm + log.personalKm);
  const gpsDistanceKm =
    log.gpsSamples && log.gpsSamples.length >= 2
      ? calculateTripDistanceKm(
          log.gpsSamples.map((sample, index) => ({
            latitude: toCoordinateNumber(sample.latitude),
            longitude: toCoordinateNumber(sample.longitude),
            recordedAt: sample.recordedAt?.toISOString() ?? `sample-${index}`,
            accuracyMeters: null,
          })),
        )
      : 0;

  return Math.max(odometerDistanceKm, splitDistanceKm, gpsDistanceKm);
}

function mapGpsSampleCreateManyData(drivingLogId: string, gpsSamples: DrivingLogGpsSampleInput[]) {
  return gpsSamples.map((sample, index) => ({
    drivingLogId,
    sampleIndex: index,
    latitude: sample.latitude,
    longitude: sample.longitude,
    accuracyMeters: sample.accuracyMeters,
    recordedAt: sample.recordedAt,
  }));
}

function mapDrivingLogGeocodeData(input: DrivingLogCreateInput) {
  return {
    startLatitude: input.startLatitude ?? null,
    startLongitude: input.startLongitude ?? null,
    endLatitude: input.endLatitude ?? null,
    endLongitude: input.endLongitude ?? null,
    startPlaceId: input.startPlaceId ?? null,
    endPlaceId: input.endPlaceId ?? null,
    startFormattedAddress: input.startFormattedAddress ?? null,
    endFormattedAddress: input.endFormattedAddress ?? null,
  };
}

async function assertJourneyInWorkspace(workspaceId: string, journeyId?: string) {
  if (!journeyId) {
    return;
  }

  const Tour = await prisma.tour.findFirst({
    where: { id: journeyId, workspaceId },
    select: { id: true },
  });

  if (!Tour) {
    throw new AppError("driving-log-invalid-Tour-reference", "DRIVING_LOG_INVALID_JOURNEY_REFERENCE");
  }
}

async function assertVehicleForTripMode(workspaceId: string, tripMode: TripMode, vehicleId?: string) {
  if (tripMode === "WALK") {
    if (vehicleId) {
      throw new AppError("driving-log-walk-trip-does-not-allow-vehicle", "DRIVING_LOG_WALK_TRIP_DOES_NOT_ALLOW_VEHICLE");
    }

    return null;
  }

  if (!vehicleId) {
    return null;
  }

  const vehicle = await prisma.vehicle.findFirst({
    where: { id: vehicleId, workspaceId },
    select: { id: true, vehicleMode: true, enableBusinessSplit: true } as never,
  }) as { id: string; vehicleMode: VehicleMode; enableBusinessSplit: boolean } | null;

  if (!vehicle) {
    throw new AppError("driving-log-invalid-vehicle-reference", "DRIVING_LOG_INVALID_VEHICLE_REFERENCE");
  }

  if (vehicle.vehicleMode !== tripMode) {
    throw new AppError("driving-log-vehicle-mode-mismatch", "DRIVING_LOG_VEHICLE_MODE_MISMATCH");
  }

  return vehicle;
}

function normalizeDrivingLogSplit(input: {
  tripMode: TripMode;
  startOdometer: number;
  endOdometer: number;
  businessKm: number;
  personalKm: number;
}, options: { enableBusinessSplit: boolean }) {
  const totalDistanceKm = Math.max(0, input.endOdometer - input.startOdometer);

  if (input.tripMode === "WALK" || !options.enableBusinessSplit) {
    return {
      businessKm: 0,
      personalKm: totalDistanceKm,
    };
  }

  return {
    businessKm: input.businessKm,
    personalKm: input.personalKm,
  };
}

function normalizeDrivingLogMetadataSplit(input: {
  tripMode: TripMode;
  startOdometer?: number;
  endOdometer?: number;
  businessKm: number;
  personalKm: number;
}, options: { enableBusinessSplit: boolean }) {
  if (input.tripMode === "WALK" || !options.enableBusinessSplit) {
    const hasOdometers = typeof input.startOdometer === "number" && typeof input.endOdometer === "number";
    const startOdometer = typeof input.startOdometer === "number" ? input.startOdometer : 0;
    const endOdometer = typeof input.endOdometer === "number" ? input.endOdometer : 0;
    const totalDistanceKm = hasOdometers
      ? Math.max(0, endOdometer - startOdometer)
      : Math.max(0, input.businessKm + input.personalKm);

    return {
      businessKm: 0,
      personalKm: totalDistanceKm,
    };
  }

  return {
    businessKm: input.businessKm,
    personalKm: input.personalKm,
  };
}

export async function listDrivingLogs(workspaceId: string) {
  const logs = await prisma.drivingLog.findMany({
    where: { workspaceId, deletedAt: null },
    include: {
      Tour: {
        select: { id: true, title: true, slug: true },
      },
      vehicle: {
        select: { id: true, name: true, enableBusinessSplit: true },
      },
      gpsSamples: {
        select: {
          latitude: true,
          longitude: true,
          recordedAt: true,
        },
        orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
      },
    },
    orderBy: { date: "desc" },
  });

  return logs.map((log) => ({
    ...log,
    computedDistanceKm: getDrivingLogComputedDistanceKm(log),
  }));
}

export async function listDrivingLogsPage(
  workspaceId: string,
  page: number,
  pageSize: number,
  filters: DrivingLogListFilters = {},
): Promise<DrivingLogListPage> {
  const safePage = Math.max(1, Math.floor(page));
  const safePageSize = Math.max(1, Math.floor(pageSize));
  const skip = (safePage - 1) * safePageSize;
  const where = {
    workspaceId,
    deletedAt: null,
    ...(filters.from || filters.to
      ? {
          date: {
            ...(filters.from ? { gte: filters.from } : {}),
            ...(filters.to ? { lte: filters.to } : {}),
          },
        }
      : {}),
    ...(filters.vehicleId ? { vehicleId: filters.vehicleId } : {}),
    ...(filters.journeyId ? { journeyId: filters.journeyId } : {}),
    ...(filters.autoGeneratedOnly
      ? {
          notes: {
            contains: "[Trip draft] Passive GPS session captured.",
          },
        }
      : {}),
  };

  const [logs, totalCount] = await prisma.$transaction([
    prisma.drivingLog.findMany({
      where,
      include: {
        Tour: {
          select: { id: true, title: true, slug: true },
        },
        vehicle: {
          select: { id: true, name: true, enableBusinessSplit: true },
        },
        gpsSamples: {
          select: {
            latitude: true,
            longitude: true,
            recordedAt: true,
          },
          orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
        },
      },
      orderBy: [{ date: "desc" }, { createdAt: "desc" }],
      skip,
      take: safePageSize,
    }),
    prisma.drivingLog.count({
      where,
    }),
  ]);

  return {
    logs: logs.map((log) => ({
      ...log,
      computedDistanceKm: getDrivingLogComputedDistanceKm(log),
    })),
    totalCount,
  };
}

export async function listDrivingLogsForExport(
  workspaceId: string,
  filters: DrivingLogExportFilters,
) {
  return prisma.drivingLog.findMany({
    where: {
      workspaceId,
      deletedAt: null,
      ...(filters.vehicleId ? { vehicleId: filters.vehicleId } : {}),
      ...(filters.journeyId ? { journeyId: filters.journeyId } : {}),
      ...(filters.autoGeneratedOnly
        ? {
            notes: {
              contains: "[Trip draft] Passive GPS session captured.",
            },
          }
        : {}),
      ...(filters.from || filters.to
        ? {
            date: {
              ...(filters.from ? { gte: filters.from } : {}),
              ...(filters.to ? { lte: filters.to } : {}),
            },
          }
        : {}),
    },
    include: {
      vehicle: { select: { id: true, name: true, registration: true, enableBusinessSplit: true } },
      Tour: { select: { id: true, title: true } },
      gpsSamples: { select: { id: true } },
    },
    orderBy: { date: "asc" },
  });
}

export async function getDrivingLogById(logId: string, workspaceId: string) {
  const log = await prisma.drivingLog.findFirst({
    where: { id: logId, workspaceId, deletedAt: null },
    include: {
      Tour: {
        select: { id: true, title: true, slug: true },
      },
      vehicle: {
        select: { id: true, name: true, enableBusinessSplit: true },
      },
      gpsSamples: {
        select: {
          latitude: true,
          longitude: true,
          recordedAt: true,
        },
        orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
      },
    },
  });

  if (!log) {
    return null;
  }

  return {
    ...log,
    computedDistanceKm: getDrivingLogComputedDistanceKm(log),
  };
}

export async function refreshDrivingLogGpsEndpointLocations(logId: string, workspaceId: string) {
  const log = await prisma.drivingLog.findFirst({
    where: { id: logId, workspaceId, deletedAt: null },
    select: {
      id: true,
      startLocation: true,
      endLocation: true,
      startFormattedAddress: true,
      endFormattedAddress: true,
      gpsSamples: {
        select: {
          latitude: true,
          longitude: true,
        },
        orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
      },
    },
  });

  if (!log || log.gpsSamples.length === 0) {
    return false;
  }

  const shouldRefreshStart = isWeakGpsLocationLabel(log.startFormattedAddress || log.startLocation);
  const shouldRefreshEnd = isWeakGpsLocationLabel(log.endFormattedAddress || log.endLocation);

  if (!shouldRefreshStart && !shouldRefreshEnd) {
    return false;
  }

  const endpoints = await reverseGeocodeTripEndpoints(
    log.gpsSamples.map((sample) => ({
      latitude: toCoordinateNumber(sample.latitude),
      longitude: toCoordinateNumber(sample.longitude),
    })),
  );
  const updateData: {
    startLocation?: string;
    endLocation?: string;
    startFormattedAddress?: string;
    endFormattedAddress?: string;
  } = {};

  if (shouldRefreshStart && endpoints.startLocation) {
    updateData.startLocation = endpoints.startLocation;
    updateData.startFormattedAddress = endpoints.startLocation;
  }

  if (shouldRefreshEnd && endpoints.endLocation) {
    updateData.endLocation = endpoints.endLocation;
    updateData.endFormattedAddress = endpoints.endLocation;
  }

  if (Object.keys(updateData).length === 0) {
    return false;
  }

  await prisma.drivingLog.update({
    where: { id: log.id },
    data: updateData,
  });

  return true;
}

export async function getLatestOdometerForWorkspace(workspaceId: string, vehicleId?: string) {
  const latest = await prisma.drivingLog.findFirst({
    where: {
      workspaceId,
      deletedAt: null,
      ...(vehicleId ? { vehicleId } : {}),
    },
    orderBy: { date: "desc" },
    select: { endOdometer: true },
  });
  return latest?.endOdometer ?? null;
}

export async function getStartOdometerForVehicle(workspaceId: string, vehicleId?: string) {
  // First, try to get the latest driving log's end odometer
  const latest = await prisma.drivingLog.findFirst({
    where: {
      workspaceId,
      deletedAt: null,
      ...(vehicleId ? { vehicleId } : {}),
    },
    orderBy: { date: "desc" },
    select: { endOdometer: true },
  });

  if (latest) {
    return latest.endOdometer;
  }

  // If no previous log and we have a vehicle ID, use the vehicle's starting odometer
  if (vehicleId) {
    const vehicle = await prisma.vehicle.findFirst({
      where: { id: vehicleId, workspaceId },
      select: { startingOdometer: true },
    });

    if (vehicle) {
      return vehicle.startingOdometer;
    }
  }

  // Fallback to 0
  return 0;
}

type TripCompletionDraftLookupInput = {
  journeyId?: string;
  tripMode: TripMode;
  vehicleId?: string;
  date: Date;
  startTime: Date;
  endTime: Date;
  startLocation: string;
  endLocation: string;
  businessKm: number;
  personalKm: number;
  notes: string;
};

export async function findMatchingTripCompletionDraft(
  input: TripCompletionDraftLookupInput,
  context: DrivingLogServiceContext,
) {
  return prisma.drivingLog.findFirst({
    where: {
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
      deletedAt: null,
      journeyId: input.journeyId ?? null,
      tripMode: input.tripMode,
      vehicleId: input.vehicleId ?? null,
      date: input.date,
      startTime: input.startTime,
      endTime: input.endTime,
      startLocation: input.startLocation,
      endLocation: input.endLocation,
      businessKm: input.businessKm,
      personalKm: input.personalKm,
      notes: input.notes,
    },
    select: { id: true },
  });
}

export async function findMatchingTripCompletionDraftByMobileTripId(
  mobileTripId: string,
  context: DrivingLogServiceContext,
) {
  return prisma.drivingLog.findFirst({
    where: {
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
      deletedAt: null,
      notes: {
        contains: `Mobile trip: ${mobileTripId}.`,
      },
    },
    select: { id: true },
  });
}

export async function createDrivingLog(input: DrivingLogCreateInput, context: DrivingLogServiceContext) {
  await assertJourneyInWorkspace(context.workspaceId, input.journeyId || undefined);
  const vehicle = await assertVehicleForTripMode(context.workspaceId, input.tripMode, input.vehicleId || undefined);
  const split = normalizeDrivingLogSplit(input, { enableBusinessSplit: vehicle?.enableBusinessSplit === true });

  return prisma.drivingLog.create({
    data: {
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
      journeyId: input.journeyId || undefined,
      tripMode: input.tripMode,
      vehicleId: input.vehicleId || undefined,
      date: input.date,
      startTime: input.startTime,
      endTime: input.endTime,
      startLocation: input.startLocation,
      endLocation: input.endLocation,
      ...mapDrivingLogGeocodeData(input),
      startOdometer: input.startOdometer,
      endOdometer: input.endOdometer,
      businessKm: split.businessKm,
      personalKm: split.personalKm,
      purpose: input.purpose,
      hasRouteSamples: input.hasRouteSamples ?? false,
      notes: input.notes,
    },
  });
}

export async function getDrivingLogRoutePreview(logId: string, workspaceId: string): Promise<DrivingLogRoutePreview | null> {
  const log = await prisma.drivingLog.findFirst({
    where: { id: logId, workspaceId, deletedAt: null },
    select: {
      id: true,
      date: true,
      startTime: true,
      endTime: true,
      startLocation: true,
      endLocation: true,
      startOdometer: true,
      endOdometer: true,
      businessKm: true,
      personalKm: true,
      purpose: true,
      vehicle: { select: { id: true, name: true, enableBusinessSplit: true } },
      Tour: { select: { id: true, title: true, slug: true } },
      gpsSamples: {
        orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
        select: {
          id: true,
          latitude: true,
          longitude: true,
          accuracyMeters: true,
          recordedAt: true,
        },
      },
    },
  });

  if (!log) {
    return null;
  }

  return {
    ...log,
    computedDistanceKm: getDrivingLogComputedDistanceKm(log),
    samples: log.gpsSamples.map((sample) => ({
      ...sample,
      latitude: Number(sample.latitude),
      longitude: Number(sample.longitude),
    })),
  };
}

export async function getDeletedDrivingLogById(logId: string, context: DrivingLogServiceContext): Promise<DeletedDrivingLog | null> {
  const deletedLog = await prisma.drivingLog.findFirst({
    where: {
      id: logId,
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
      deletedAt: { not: null },
    },
    select: { id: true, deletedAt: true, updatedAt: true },
  });

  if (!deletedLog?.deletedAt) {
    return null;
  }

  return {
    id: deletedLog.id,
    deletedAt: deletedLog.deletedAt,
    updatedAt: deletedLog.updatedAt,
  };
}

export async function listDeletedDrivingLogs(workspaceId: string): Promise<DeletedDrivingLog[]> {
  const deletedLogs = await prisma.drivingLog.findMany({
    where: { workspaceId, deletedAt: { not: null } },
    orderBy: { deletedAt: "desc" },
    select: { id: true, deletedAt: true, updatedAt: true },
  });

  return deletedLogs.flatMap((log) =>
    log.deletedAt ? [{ id: log.id, deletedAt: log.deletedAt, updatedAt: log.updatedAt }] : [],
  );
}

export async function listMobileDrivingLogSummaries(workspaceId: string): Promise<MobileDrivingLogSummary[]> {
  const logs = await prisma.drivingLog.findMany({
    where: { workspaceId, deletedAt: null },
    orderBy: [{ updatedAt: "desc" }, { date: "desc" }],
    take: 100,
    select: {
        id: true,
        journeyId: true,
        tripMode: true,
        vehicleId: true,
        date: true,
        startTime: true,
        endTime: true,
        startLocation: true,
        endLocation: true,
        startFormattedAddress: true,
        endFormattedAddress: true,
        startOdometer: true,
        endOdometer: true,
        businessKm: true,
        personalKm: true,
        purpose: true,
        updatedAt: true,
        gpsSamples: {
          select: {
            latitude: true,
            longitude: true,
            recordedAt: true,
          },
          orderBy: [{ sampleIndex: "asc" }, { recordedAt: "asc" }],
        },
          vehicle: {
            select: {
              name: true,
            },
          },
        Tour: {
          select: {
            title: true,
          },
        },
      },
  });

  return logs.map((log) => ({
      id: log.id,
      journeyId: log.journeyId,
      journeyTitle: log.Tour?.title ?? null,
      tripMode: log.tripMode,
      vehicleId: log.vehicleId,
    vehicleName: log.vehicle?.name ?? null,
    date: log.date,
    startedAt: log.startTime,
    endedAt: log.endTime,
      startOdometer: log.startOdometer,
      endOdometer: log.endOdometer,
      businessKm: log.businessKm,
      personalKm: log.personalKm,
      purpose: log.purpose,
      startLocation: log.startFormattedAddress ?? log.startLocation,
      endLocation: log.endFormattedAddress ?? log.endLocation,
      computedDistanceKm: getDrivingLogComputedDistanceKm(log),
      updatedAt: log.updatedAt,
    }));
}

export async function createDrivingLogWithGpsSamples(
  input: DrivingLogCreateInput,
  gpsSamples: DrivingLogGpsSampleInput[],
  context: DrivingLogServiceContext,
) {
  await assertJourneyInWorkspace(context.workspaceId, input.journeyId || undefined);
  await assertVehicleForTripMode(context.workspaceId, input.tripMode, input.vehicleId || undefined);

  return prisma.$transaction(async (tx) => {
    const draft = await tx.drivingLog.create({
      data: {
        workspaceId: context.workspaceId,
        createdByUserId: context.userId,
        journeyId: input.journeyId || undefined,
        tripMode: input.tripMode,
        vehicleId: input.vehicleId || undefined,
        date: input.date,
        startTime: input.startTime,
        endTime: input.endTime,
        startLocation: input.startLocation,
        endLocation: input.endLocation,
        ...mapDrivingLogGeocodeData(input),
        startOdometer: input.startOdometer,
        endOdometer: input.endOdometer,
        businessKm: input.businessKm,
        personalKm: input.personalKm,
        purpose: input.purpose,
        hasRouteSamples: input.hasRouteSamples ?? gpsSamples.length > 0,
        notes: input.notes,
      },
    });

    if (gpsSamples.length > 0) {
      await tx.drivingLogGpsSample.createMany({
        data: mapGpsSampleCreateManyData(draft.id, gpsSamples),
      });
    }

    return draft;
  });
}

export async function appendDrivingLogGpsSamples(
  logId: string,
  gpsSamples: DrivingLogGpsSampleInput[],
  context: DrivingLogServiceContext,
) {
  if (gpsSamples.length === 0) {
    return { count: 0 };
  }

  const existing = await prisma.drivingLog.findFirst({
    where: {
      id: logId,
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
      deletedAt: null,
    },
    select: { id: true },
  });

  if (!existing) {
    throw new AppError("driving-log-not-found", "DRIVING_LOG_NOT_FOUND");
  }

  const result = await prisma.drivingLogGpsSample.createMany({
    data: mapGpsSampleCreateManyData(logId, gpsSamples),
    skipDuplicates: true,
  });

  await prisma.drivingLog.update({
    where: { id: logId },
    data: { hasRouteSamples: true },
  });

  return result;
}

export async function updateDrivingLogTripMetadata(
  logId: string,
    input: {
      journeyId?: string | null;
      tripMode?: TripMode;
      vehicleId?: string | null;
    startLocation?: string | null;
    endLocation?: string | null;
    startFormattedAddress?: string | null;
    endFormattedAddress?: string | null;
    startOdometer?: number;
    endOdometer?: number;
    businessKm: number;
    personalKm: number;
    purpose?: string | null;
    hasRouteSamples?: boolean;
  },
  context: DrivingLogServiceContext,
) {
  const existing = await prisma.drivingLog.findFirst({
    where: {
      id: logId,
      workspaceId: context.workspaceId,
      createdByUserId: context.userId,
    },
    select: { id: true, deletedAt: true },
  });

  if (!existing) {
    throw new AppError("driving-log-not-found", "DRIVING_LOG_NOT_FOUND");
  }

  if (existing.deletedAt) {
    return existing;
  }

  await assertJourneyInWorkspace(context.workspaceId, input.journeyId || undefined);
  const vehicle = await assertVehicleForTripMode(context.workspaceId, input.tripMode ?? "DRIVE", input.vehicleId ?? undefined);
  const split = normalizeDrivingLogMetadataSplit(
    {
      tripMode: input.tripMode ?? "DRIVE",
      startOdometer: input.startOdometer,
      endOdometer: input.endOdometer,
      businessKm: input.businessKm,
      personalKm: input.personalKm,
    },
    { enableBusinessSplit: vehicle?.enableBusinessSplit === true },
  );

  return prisma.drivingLog.update({
      where: { id: logId },
      data: {
        journeyId: input.journeyId ?? null,
        ...(input.tripMode ? { tripMode: input.tripMode } : {}),
        vehicleId: input.vehicleId ?? null,
      ...(typeof input.startLocation === "string" ? { startLocation: input.startLocation } : {}),
      ...(typeof input.endLocation === "string" ? { endLocation: input.endLocation } : {}),
      ...(typeof input.startFormattedAddress === "string" ? { startFormattedAddress: input.startFormattedAddress } : {}),
      ...(typeof input.endFormattedAddress === "string" ? { endFormattedAddress: input.endFormattedAddress } : {}),
      ...(typeof input.startOdometer === "number" ? { startOdometer: input.startOdometer } : {}),
      ...(typeof input.endOdometer === "number" ? { endOdometer: input.endOdometer } : {}),
        businessKm: split.businessKm,
        personalKm: split.personalKm,
      ...(typeof input.purpose === "string" || input.purpose === null ? { purpose: input.purpose } : {}),
      ...(typeof input.hasRouteSamples === "boolean" ? { hasRouteSamples: input.hasRouteSamples } : {}),
      },
    });
}

export async function updateDrivingLog(logId: string, input: DrivingLogCreateInput, workspaceId: string) {
  const existing = await prisma.drivingLog.findFirst({
    where: { id: logId, workspaceId },
    select: { id: true, deletedAt: true },
  });

  if (!existing) {
    throw new AppError("driving-log-not-found", "DRIVING_LOG_NOT_FOUND");
  }

  if (existing.deletedAt) {
    return existing;
  }

  await assertJourneyInWorkspace(workspaceId, input.journeyId || undefined);
  const vehicle = await assertVehicleForTripMode(workspaceId, input.tripMode, input.vehicleId || undefined);
  const split = normalizeDrivingLogSplit(input, { enableBusinessSplit: vehicle?.enableBusinessSplit === true });

  return prisma.drivingLog.update({
    where: { id: logId },
    data: {
      journeyId: input.journeyId || undefined,
      tripMode: input.tripMode,
      vehicleId: input.vehicleId ?? undefined,
      date: input.date,
      startTime: input.startTime,
      endTime: input.endTime,
      startLocation: input.startLocation,
      endLocation: input.endLocation,
      ...mapDrivingLogGeocodeData(input),
      startOdometer: input.startOdometer,
      endOdometer: input.endOdometer,
      businessKm: split.businessKm,
      personalKm: split.personalKm,
      purpose: input.purpose,
      ...(typeof input.hasRouteSamples === "boolean" ? { hasRouteSamples: input.hasRouteSamples } : {}),
      notes: input.notes,
    },
  });
}

export async function deleteDrivingLog(logId: string, workspaceId: string) {
  const existing = await prisma.drivingLog.findFirst({
    where: { id: logId, workspaceId },
    select: { id: true, deletedAt: true },
  });

  if (!existing) {
    throw new AppError("driving-log-not-found", "DRIVING_LOG_NOT_FOUND");
  }

  if (existing.deletedAt) {
    return existing;
  }

  return prisma.$transaction(async (tx) => {
    await tx.externalMediaLink.updateMany({
      where: {
        workspaceId,
        entityType: "TRIP",
        entityId: logId,
        deletedAt: null,
      },
      data: {
        deletedAt: new Date(),
      },
    });

    return tx.drivingLog.update({
      where: { id: logId },
      data: { deletedAt: new Date() },
    });
  });
}
