import Link from "next/link";
import { notFound } from "next/navigation";
import { formatDistanceKm } from "@gigeze/shared";
import { ActionSubmitButton } from "@/components/forms/action-submit-button";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { VehicleOdometerFields } from "@/components/forms/vehicle-odometer-fields";
import { AddressAutocompleteField } from "@/components/maps/address-autocomplete-field";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button-variants";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { requireCurrentWorkspace } from "@/lib/auth/workspace";
import { deleteDrivingLogAction, updateDrivingLogAction } from "@/features/driving-logs/actions";
import { getDrivingLogById, refreshDrivingLogGpsEndpointLocations } from "@/features/driving-logs/service";
import { listJourneys } from "@/features/tours/service";
import { getLatestOdometerForVehicle, listVehicles } from "@/features/vehicles/service";
import { formatDateInputValue, formatTimeInputValue } from "@/lib/datetime";

function isAutoGeneratedDrivingLog(notes?: string | null) {
  return (notes ?? "").includes("[Trip draft] Passive GPS session captured.");
}

export default async function EditDrivingLogPage({
  params,
}: {
  params: Promise<{ logId: string }>;
}) {
  const { logId } = await params;
  const workspace = await requireCurrentWorkspace();
  const [initialLog, Tours, vehicles] = await Promise.all([
    getDrivingLogById(logId, workspace.id),
    listJourneys(workspace.id),
    listVehicles(workspace.id),
  ]);
  const vehicleOdometerEntries = await Promise.all(
    vehicles.map(async (vehicle) => [vehicle.id, await getLatestOdometerForVehicle(workspace.id, vehicle.id)] as const),
  );
  const vehicleOdometerMap = Object.fromEntries(vehicleOdometerEntries);
  const vehicleOptions = vehicles.map((vehicle) => ({
    id: vehicle.id,
    name: vehicle.name,
    isDefault: vehicle.isDefault,
    enableBusinessSplit: vehicle.enableBusinessSplit,
  }));

  if (!initialLog) {
    notFound();
  }

  let log = initialLog;
  if (isAutoGeneratedDrivingLog(log.notes)) {
    const refreshedLocations = await refreshDrivingLogGpsEndpointLocations(log.id, workspace.id);
    if (refreshedLocations) {
      log = await getDrivingLogById(log.id, workspace.id) ?? log;
    }
  }

  const totalDistance = log.computedDistanceKm;
  const isAutoGenerated = isAutoGeneratedDrivingLog(log.notes);
  const exportSearch = new URLSearchParams({
    ...(log.vehicle?.id ? { vehicleId: log.vehicle.id } : {}),
    ...(log.Tour?.id ? { journeyId: log.Tour.id } : {}),
  }).toString();
  const exportHref = exportSearch ? `/dashboard/logs/driving/export?${exportSearch}` : "/dashboard/logs/driving/export";

  return (
    <section className="w-full space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">Edit driving log</h1>
          <p className="text-muted-foreground">Mode: {log.tripMode} • Total distance for this entry: {formatDistanceKm(totalDistance, { tripType: log.tripMode === "WALK" ? "walking" : log.tripMode === "RIDE" ? "ride" : "driving" })}.</p>
          {isAutoGenerated ? (
            <div className="mt-2 space-y-2">
              <Badge>Auto-generated</Badge>
              <p className="text-sm text-muted-foreground">Created from GPS tracking</p>
            </div>
          ) : null}
        </div>
        <div className="flex flex-wrap gap-2">
          <Link href="/dashboard/logs/driving" className={buttonVariants({ variant: "outline" })}>
            Back to logs
          </Link>
          <Link href={exportHref} className={buttonVariants({ variant: "outline" })}>
            Go to export
          </Link>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Driving log details</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={updateDrivingLogAction} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            <input type="hidden" name="logId" value={log.id} />

            <div className="space-y-2 md:col-span-2 xl:col-span-3">
              <Label htmlFor="journeyId">Tour (optional)</Label>
              <select
                id="journeyId"
                name="journeyId"
                defaultValue={log.Tour?.id ?? ""}
                className="w-full"
              >
                <option value="">No Tour link</option>
                {Tours.map((Tour) => (
                  <option key={Tour.id} value={Tour.id}>
                    {Tour.title}
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="date">Date</Label>
              <Input id="date" name="date" type="date" defaultValue={formatDateInputValue(log.date)} required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="startTime">Start time (optional)</Label>
              <Input id="startTime" name="startTime" type="time" defaultValue={formatTimeInputValue(log.startTime)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="endTime">End time (optional)</Label>
              <Input id="endTime" name="endTime" type="time" defaultValue={formatTimeInputValue(log.endTime)} />
            </div>
            <AddressAutocompleteField
              label="Start location"
              name="startLocation"
              defaultValue={log.startLocation ?? ""}
              placeholder="Coburg VIC"
              helperText="Use suburb/state or a recognisable place name."
              formattedAddressName="startFormattedAddress"
              placeIdName="startPlaceId"
              latitudeName="startLatitude"
              longitudeName="startLongitude"
              defaultFormattedAddress={log.startFormattedAddress}
              defaultPlaceId={log.startPlaceId}
              defaultLatitude={log.startLatitude}
              defaultLongitude={log.startLongitude}
            />
            <AddressAutocompleteField
              label="End location"
              name="endLocation"
              defaultValue={log.endLocation ?? ""}
              placeholder="Brunswick VIC"
              helperText="Use suburb/state or a recognisable place name."
              formattedAddressName="endFormattedAddress"
              placeIdName="endPlaceId"
              latitudeName="endLatitude"
              longitudeName="endLongitude"
              defaultFormattedAddress={log.endFormattedAddress}
              defaultPlaceId={log.endPlaceId}
              defaultLatitude={log.endLatitude}
              defaultLongitude={log.endLongitude}
            />
            <VehicleOdometerFields
              vehicles={vehicleOptions}
              vehicleOdometerMap={vehicleOdometerMap}
              defaultVehicleId={log.vehicle?.id ?? undefined}
              initialStartOdometer={log.startOdometer}
              initialEndOdometer={log.endOdometer}
              initialBusinessKm={log.businessKm}
              initialPersonalKm={log.personalKm}
              initialTripMode={log.tripMode}
              className="md:col-span-2 xl:col-span-3"
            />
            <div className="space-y-2 md:col-span-2 xl:col-span-3">
              <Label htmlFor="purpose">Purpose</Label>
              <Input id="purpose" name="purpose" defaultValue={log.purpose ?? ""} placeholder="Client meeting" />
              <p className="text-xs text-muted-foreground">
                Examples: Client meeting, Travel between job sites, Personal errand, Fuel Gig.
              </p>
            </div>
            <div className="space-y-2 md:col-span-2 xl:col-span-3">
              <Label htmlFor="notes">Notes</Label>
              <Textarea id="notes" name="notes" rows={4} defaultValue={log.notes ?? ""} />
            </div>

            <ActionSubmitButton label="Save driving log" pendingLabel="Saving..." className="md:col-span-2 md:w-fit xl:col-span-3" />
          </form>
        </CardContent>
      </Card>

      <Card className="max-w-3xl">
        <CardHeader>
          <CardTitle>Delete entry</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={deleteDrivingLogAction} id={`delete-driving-log-${log.id}`}>
            <input type="hidden" name="logId" value={log.id} />
            <ConfirmSubmitButton
              formId={`delete-driving-log-${log.id}`}
              triggerLabel="Delete driving log"
              title="Delete driving log?"
              description="This driving log entry will be permanently removed."
              confirmLabel="Delete driving log"
            />
          </form>
        </CardContent>
      </Card>
    </section>
  );
}
