import Link from "next/link";
import { formatDistanceKm } from "@gigeze/shared";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { ExportDownloadLink } from "@/components/forms/export-download-link";
import { buttonVariants } from "@/components/ui/button-variants";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { requireCurrentWorkspace } from "@/lib/auth/workspace";
import { formatDateInputValue, formatTimeInputValue, parseAppDateEnd, parseAppDateStart } from "@/lib/datetime";
import {
  getDrivingLogExportDistance,
  getDrivingLogExportSummary,
} from "@/features/driving-logs/export";
import { listDrivingLogsForExport } from "@/features/driving-logs/service";
import { listJourneys } from "@/features/tours/service";
import { listVehicles } from "@/features/vehicles/service";

type ExportSearchParams = {
  from?: string;
  to?: string;
  vehicleId?: string;
  journeyId?: string;
  source?: string;
};

function parseDateStart(value?: string) {
  return parseAppDateStart(value);
}

function parseDateEnd(value?: string) {
  return parseAppDateEnd(value);
}

function buildExportHref(params: ExportSearchParams) {
  const query = new URLSearchParams();

  if (params.from) {
    query.set("from", params.from);
  }
  if (params.to) {
    query.set("to", params.to);
  }
  if (params.vehicleId) {
    query.set("vehicleId", params.vehicleId);
  }
  if (params.journeyId) {
    query.set("journeyId", params.journeyId);
  }
  if (params.source) {
    query.set("source", params.source);
  }

  const queryString = query.toString();
  return queryString ? `/api/logs/driving/export?${queryString}` : "/api/logs/driving/export";
}

export default async function DrivingLogExportPage({
  searchParams,
}: {
  searchParams: Promise<ExportSearchParams>;
}) {
  const workspace = await requireCurrentWorkspace();
  const params = await searchParams;

  const [vehicles, Tours] = await Promise.all([
    listVehicles(workspace.id),
    listJourneys(workspace.id),
  ]);

  const selectedVehicleId =
    params.vehicleId && vehicles.some((vehicle) => vehicle.id === params.vehicleId)
      ? params.vehicleId
      : "";
  const selectedJourneyId =
    params.journeyId && Tours.some((Tour) => Tour.id === params.journeyId)
      ? params.journeyId
      : "";
  const autoGeneratedOnly = params.source === "auto";

  const hasFilters = Boolean(params.from || params.to || selectedVehicleId || selectedJourneyId || autoGeneratedOnly);
  const logs = hasFilters
    ? await listDrivingLogsForExport(workspace.id, {
        from: parseDateStart(params.from),
        to: parseDateEnd(params.to),
        vehicleId: selectedVehicleId || undefined,
        journeyId: selectedJourneyId || undefined,
        autoGeneratedOnly,
      })
    : [];

  const invalidLogs = logs.filter((log) => {
    const totalKm = getDrivingLogExportDistance(log);
    return log.endOdometer < log.startOdometer || log.businessKm + log.personalKm !== totalKm;
  });
  const invalidMessages = invalidLogs.map((log) => {
    const distance = getDrivingLogExportDistance(log);
    if (log.endOdometer < log.startOdometer) {
      return `${formatDateInputValue(log.date)}: odometer inconsistency (${log.startOdometer} -> ${log.endOdometer}).`;
    }

    return `${formatDateInputValue(log.date)}: mismatched split (business ${log.businessKm} + personal ${log.personalKm} != distance ${distance}).`;
  });
  const periodStart = parseDateStart(params.from);
  const periodEnd = parseDateEnd(params.to);
  const summary = getDrivingLogExportSummary(logs, {
    periodStart,
    periodEnd,
    workspaceName: workspace.name,
  });
  const missingDetails = [
    summary.missingOdometerCount
      ? `${summary.missingOdometerCount} missing odometer ${summary.missingOdometerCount === 1 ? "reading" : "readings"}`
      : null,
    summary.missingLocationsCount
      ? `${summary.missingLocationsCount} missing start/end ${summary.missingLocationsCount === 1 ? "location" : "locations"}`
      : null,
    summary.missingPurposeCount
      ? `${summary.missingPurposeCount} missing explicit ${summary.missingPurposeCount === 1 ? "purpose" : "purposes"}`
      : null,
    summary.missingSplitCount
      ? `${summary.missingSplitCount} missing business/personal ${summary.missingSplitCount === 1 ? "split" : "splits"}`
      : null,
  ].filter((message): message is string => Boolean(message));
  const selectedVehicleName = selectedVehicleId
    ? vehicles.find((vehicle) => vehicle.id === selectedVehicleId)?.name
    : undefined;
  const generatedAt = new Date();

  const downloadHref = buildExportHref({
    from: params.from,
    to: params.to,
    vehicleId: selectedVehicleId || undefined,
    journeyId: selectedJourneyId || undefined,
    source: autoGeneratedOnly ? "auto" : undefined,
  });

  return (
    <section className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">ATO-style driving log export</h1>
          <p className="text-muted-foreground">
            Exports are designed to assist accountant review and ATO-style logbook record keeping. Confirm details with your accountant.
          </p>
        </div>
        <Link href="/dashboard/logs/driving" className={buttonVariants({ variant: "outline" })}>
          Back to driving logs
        </Link>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Export filters</CardTitle>
        </CardHeader>
        <CardContent>
          <form action="" method="GET" className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">
            <div className="space-y-2">
              <Label htmlFor="from">From date</Label>
              <Input id="from" name="from" type="date" defaultValue={params.from ?? ""} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="to">To date</Label>
              <Input id="to" name="to" type="date" defaultValue={params.to ?? ""} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="vehicleId">Vehicle</Label>
              <select id="vehicleId" name="vehicleId" defaultValue={selectedVehicleId} className="w-full">
                <option value="">All vehicles</option>
                {vehicles.map((vehicle) => (
                  <option key={vehicle.id} value={vehicle.id}>
                    {vehicle.name}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="journeyId">Tour</Label>
              <select id="journeyId" name="journeyId" defaultValue={selectedJourneyId} className="w-full">
                <option value="">All Tours</option>
                {Tours.map((Tour) => (
                  <option key={Tour.id} value={Tour.id}>
                    {Tour.title}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="source">Source</Label>
              <select id="source" name="source" defaultValue={autoGeneratedOnly ? "auto" : ""} className="w-full">
                <option value="">All entries</option>
                <option value="auto">Auto-generated only</option>
              </select>
            </div>
            <div className="md:col-span-2 lg:col-span-5 flex flex-wrap items-center gap-2">
              <button type="submit" className={buttonVariants({})}>
                Preview records
              </button>
              {hasFilters ? (
                <ExportDownloadLink href={downloadHref} />
              ) : null}
            </div>
          </form>
        </CardContent>
      </Card>

      {hasFilters ? (
        <Card>
          <CardHeader>
            <CardTitle>ATO-style logbook period summary</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Period start</p>
                <p className="mt-1 text-base font-semibold">{summary.periodStart || "Not selected"}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Period end</p>
                <p className="mt-1 text-base font-semibold">{summary.periodEnd || "Not selected"}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Total days</p>
                <p className="mt-1 text-base font-semibold">{summary.totalDays}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Generated</p>
                <p className="mt-1 text-base font-semibold">
                  {formatDateInputValue(generatedAt)} {formatTimeInputValue(generatedAt)}
                </p>
              </div>
            </div>
            {selectedVehicleName ? (
              <p className="text-muted-foreground">Vehicle context: <span className="font-medium text-foreground">{selectedVehicleName}</span></p>
            ) : null}
            <p className="text-muted-foreground">
              Workspace: <span className="font-medium text-foreground">{workspace.name}</span>
            </p>
            <p className="text-muted-foreground">
              Vehicles included: <span className="font-medium text-foreground">{summary.vehiclesIncluded.join(", ") || "None"}</span>
            </p>
            <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Total trips</p>
                <p className="mt-1 text-base font-semibold">{summary.tripsInRange}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Total distance</p>
                <p className="mt-1 text-base font-semibold">{formatDistanceKm(summary.totalDistance)}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Business km</p>
                <p className="mt-1 text-base font-semibold">{formatDistanceKm(summary.businessKm)}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Personal km</p>
                <p className="mt-1 text-base font-semibold">{formatDistanceKm(summary.personalKm)}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Business use %</p>
                <p className="mt-1 text-base font-semibold">{summary.businessUsePercentage.toFixed(1)}%</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Missing locations</p>
                <p className="mt-1 text-base font-semibold">{summary.missingLocationsCount}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Missing explicit purpose</p>
                <p className="mt-1 text-base font-semibold">{summary.missingPurposeCount}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">Missing odometer</p>
                <p className="mt-1 text-base font-semibold">{summary.missingOdometerCount}</p>
              </div>
              <div className="rounded-md border border-border/70 bg-muted/20 p-3">
                <p className="text-xs text-muted-foreground">GPS evidence count</p>
                <p className="mt-1 text-base font-semibold">{summary.gpsEvidenceCount}</p>
              </div>
            </div>
            {summary.isUnderTwelveWeeks ? (
              <Alert className="border-amber-700/40 bg-amber-950/10">
                <AlertTitle>12-week representative period note</AlertTitle>
                <AlertDescription>
                  ATO logbooks are commonly based on a continuous 12-week representative period. Confirm your record-keeping requirements with your accountant.
                </AlertDescription>
              </Alert>
            ) : null}
            {missingDetails.length ? (
              <Alert className="border-amber-700/40 bg-amber-950/10">
                <AlertTitle>Review before export</AlertTitle>
                <AlertDescription>
                  Selected records have {missingDetails.join(", ")}. Add the missing details where available before sharing with your accountant.
                </AlertDescription>
              </Alert>
            ) : null}
            {invalidLogs.length === 0 && missingDetails.length === 0 && logs.length > 0 ? (
              <Badge className="bg-emerald-600 text-white hover:bg-emerald-600">✓ Ready for export</Badge>
            ) : null}
          </CardContent>
        </Card>
      ) : null}

      {invalidLogs.length ? (
        <Alert variant="destructive">
          <AlertTitle>Some entries need review before export</AlertTitle>
          <AlertDescription>
            <p>
              {invalidLogs.length} log {invalidLogs.length === 1 ? "entry appears" : "entries appear"} inconsistent.
              Check the issues below before sharing.
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-4">
              {invalidMessages.map((message) => (
                <li key={message}>{message}</li>
              ))}
            </ul>
          </AlertDescription>
        </Alert>
      ) : null}

      {hasFilters ? (
        <Card>
          <CardHeader>
            <CardTitle>Preview ({logs.length} entries)</CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            {logs.length
              ? "Your selected records are ready for export."
              : "No driving logs matched these filters. Try expanding the date range or clearing optional filters."}
          </CardContent>
        </Card>
      ) : null}
    </section>
  );
}
