"use client";

import Link from "next/link";
import { Fragment, useState } from "react";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { TripLogRouteMap } from "@/components/driving-logs/trip-log-route-map";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button-variants";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { deleteDrivingLogAction } from "@/features/driving-logs/actions";
import { getNextExpandedLogId, getRouteEndpoint, type DrivingLogRouteSample } from "@/features/driving-logs/route-preview";

export type TripLogTableRow = {
  id: string;
  dateText: string;
  timeText: string;
  tripModeText: string;
  vehicleText: string;
  journeyText: string;
  startLocationText: string;
  endLocationText: string;
  startOdometer: number;
  endOdometer: number;
  totalText: string;
  businessText?: string;
  personalText?: string;
  splitText?: string;
  showBusinessSplit: boolean;
  isAutoGenerated: boolean;
};

type TripLogRouteResponse = {
  id: string;
  samples: DrivingLogRouteSample[];
};

type RouteLoadState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "loaded"; samples: DrivingLogRouteSample[] }
  | { status: "error"; message: string };

type ExpandableTripLogsTableProps = {
  rows: TripLogTableRow[];
};

async function fetchRouteSamples(logId: string): Promise<DrivingLogRouteSample[]> {
  const response = await fetch(getRouteEndpoint(logId), {
    headers: { Accept: "application/json" },
  });

  if (!response.ok) {
    throw new Error(`Route preview failed with HTTP ${response.status}.`);
  }

  const data = (await response.json()) as TripLogRouteResponse;
  return Array.isArray(data.samples) ? data.samples : [];
}

export function ExpandableTripLogsTable({ rows }: ExpandableTripLogsTableProps) {
  const [expandedLogId, setExpandedLogId] = useState<string | null>(null);
  const [routeCache, setRouteCache] = useState<Record<string, RouteLoadState>>({});
  const expandedRow = expandedLogId ? rows.find((row) => row.id === expandedLogId) ?? null : null;
  const expandedRouteState = expandedLogId ? routeCache[expandedLogId] ?? { status: "idle" as const } : { status: "idle" as const };

  function handleToggleRoute(logId: string) {
    const nextExpandedLogId = getNextExpandedLogId(expandedLogId, logId);
    setExpandedLogId(nextExpandedLogId);

    if (!nextExpandedLogId || routeCache[nextExpandedLogId]?.status) {
      return;
    }

    setRouteCache((current) => ({
      ...current,
      [nextExpandedLogId]: { status: "loading" },
    }));

    fetchRouteSamples(nextExpandedLogId)
      .then((samples) => {
        setRouteCache((current) => ({
          ...current,
          [nextExpandedLogId]: { status: "loaded", samples },
        }));
      })
      .catch((error: unknown) => {
        setRouteCache((current) => ({
          ...current,
          [nextExpandedLogId]: {
            status: "error",
            message: error instanceof Error ? error.message : "Unable to load route preview.",
          },
        }));
      });
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-10">
            <span className="sr-only">Expand route</span>
          </TableHead>
          <TableHead>Date</TableHead>
          <TableHead>Time</TableHead>
          <TableHead>Mode</TableHead>
          <TableHead>Vehicle</TableHead>
          <TableHead>Tour</TableHead>
          <TableHead>Route</TableHead>
          <TableHead>Start</TableHead>
          <TableHead>End</TableHead>
          <TableHead>Total</TableHead>
          <TableHead>Split</TableHead>
          <TableHead>Actions</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {rows.map((row) => {
          const isExpanded = expandedLogId === row.id;

          return (
            <Fragment key={row.id}>
              <TableRow aria-expanded={isExpanded}>
                <TableCell className="w-10 pr-0">
                  <button
                    type="button"
                    aria-expanded={isExpanded}
                    aria-label={`${isExpanded ? "Collapse" : "Expand"} route preview for ${row.dateText} ${row.timeText}`}
                    className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-border/70 bg-background text-muted-foreground transition hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                    onClick={() => handleToggleRoute(row.id)}
                  >
                    <span className={`text-base leading-none transition-transform ${isExpanded ? "rotate-90" : ""}`}>›</span>
                  </button>
                </TableCell>
                <TableCell>{row.dateText}</TableCell>
                <TableCell>{row.timeText}</TableCell>
                <TableCell>
                  <Badge variant="outline">{row.tripModeText}</Badge>
                </TableCell>
                <TableCell>
                  <div className="space-y-1">
                    <p>{row.vehicleText}</p>
                    {row.isAutoGenerated ? <Badge variant="outline">Auto-generated</Badge> : null}
                  </div>
                </TableCell>
                <TableCell>{row.journeyText}</TableCell>
                <TableCell>
                  <div className="space-y-1 text-sm">
                    <p>{row.startLocationText}</p>
                    <p className="text-muted-foreground">to {row.endLocationText}</p>
                  </div>
                </TableCell>
                <TableCell>{row.startOdometer}</TableCell>
                <TableCell>{row.endOdometer}</TableCell>
                <TableCell>
                  <div className="space-y-1">
                    <p className="font-medium">{row.totalText}</p>
                    <Badge variant="outline">Computed distance</Badge>
                  </div>
                </TableCell>
                <TableCell>
                  {row.showBusinessSplit ? (
                    <div className="space-y-1 text-sm">
                      {row.businessText ? <p>{row.businessText}</p> : null}
                      {row.personalText ? <p className="text-muted-foreground">{row.personalText}</p> : null}
                    </div>
                  ) : null}
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-2">
                    <Link href={`/dashboard/logs/driving/${row.id}/edit`} className={buttonVariants({ variant: "outline", size: "sm" })}>
                      Edit
                    </Link>
                    <form action={deleteDrivingLogAction} id={`delete-driving-log-${row.id}`}>
                      <input type="hidden" name="logId" value={row.id} />
                      <ConfirmSubmitButton
                        formId={`delete-driving-log-${row.id}`}
                        triggerLabel="Delete"
                        title="Delete driving log?"
                        description="This driving log entry will be permanently removed."
                        confirmLabel="Delete"
                        size="sm"
                      />
                    </form>
                  </div>
                </TableCell>
              </TableRow>
              {isExpanded && expandedRow ? (
                <TableRow className="bg-muted/12 hover:bg-muted/12">
                  <TableCell colSpan={12} className="whitespace-normal px-4 py-4">
                    <div className="rounded-xl border border-border/70 bg-background/95 p-4 shadow-sm">
                      <div className="mb-3 flex flex-wrap items-start justify-between gap-3 rounded-lg border border-border/60 bg-muted/20 px-4 py-3">
                        <div>
                          <p className="text-sm font-semibold text-foreground">{expandedRow.vehicleText}</p>
                          <p className="text-xs text-muted-foreground">
                            {expandedRow.dateText} · {expandedRow.timeText} · {expandedRow.tripModeText} · {expandedRow.journeyText}
                          </p>
                        </div>
                        <div className="flex flex-wrap gap-2 text-xs">
                          <Badge variant="secondary">{expandedRow.totalText}</Badge>
                          {expandedRow.showBusinessSplit && expandedRow.splitText ? <Badge variant="outline">{expandedRow.splitText}</Badge> : null}
                        </div>
                      </div>

                      {expandedRouteState.status === "loaded" ? (
                        <TripLogRouteMap distanceText={expandedRow.totalText} samples={expandedRouteState.samples} />
                      ) : expandedRouteState.status === "error" ? (
                        <div className="flex h-[280px] flex-col items-center justify-center rounded-lg border border-dashed border-border/80 bg-muted/20 p-6 text-center">
                          <p className="text-base font-semibold text-foreground">Unable to load route preview</p>
                          <p className="mt-1 max-w-md text-sm text-muted-foreground">{expandedRouteState.message}</p>
                          <button
                            type="button"
                            className="mt-3 rounded-md border border-border bg-background px-3 py-1.5 text-xs font-semibold text-foreground hover:bg-muted"
                            onClick={() => {
                              setRouteCache((current) => {
                                const next = { ...current };
                                delete next[row.id];
                                return next;
                              });
                            }}
                          >
                            Retry
                          </button>
                        </div>
                      ) : (
                        <div className="flex h-[280px] items-center justify-center rounded-lg border border-border/70 bg-muted/20 text-sm font-medium text-muted-foreground">
                          Loading route preview...
                        </div>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ) : null}
            </Fragment>
          );
        })}
      </TableBody>
    </Table>
  );
}
