import Link from "next/link";
import { formatDistanceKm } from "@gigeze/shared";
import { ExpandableTripLogsTable, type TripLogTableRow } from "@/components/driving-logs/expandable-trip-logs-table";
import { EmptyState } from "@/components/layout/empty-state";
import { ConfirmSubmitButton } from "@/components/forms/confirm-submit-button";
import { VehicleOdometerFields } from "@/components/forms/vehicle-odometer-fields";
import { ActionSubmitButton } from "@/components/forms/action-submit-button";
import { AddressAutocompleteField } from "@/components/maps/address-autocomplete-field";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button-variants";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createDrivingLogAction, deleteDrivingLogAction } from "@/features/driving-logs/actions";
import { getDrivingLogSplitDisplay } from "@/features/driving-logs/display";
import { listDrivingLogsPage } from "@/features/driving-logs/service";
import { listJourneys } from "@/features/tours/service";
import { getLatestOdometerForVehicle, listVehicles } from "@/features/vehicles/service";
import { requireCurrentWorkspace } from "@/lib/auth/workspace";
import { formatInAppTimeZone, parseAppDateEnd, parseAppDateStart } from "@/lib/datetime";

const LOGS_PAGE_SIZE = 10;

type DrivingLogLog = Awaited<ReturnType<typeof listDrivingLogsPage>>["logs"][number];

type DrivingLogsSearchParams = {
  from?: string;
  to?: string;
  journeyId?: string;
  vehicleId?: string;
  source?: string;
  startLocation?: string;
  endLocation?: string;
  startOdometer?: string;
  page?: string;
};

function formatDate(value: Date) {
  return formatInAppTimeZone(value, {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatTime(value?: Date | null) {
  if (!value) {
    return null;
  }

  return formatInAppTimeZone(value, {
    hour: "2-digit",
    minute: "2-digit",
  }, "");
}

function formatTimeRange(startTime?: Date | null, endTime?: Date | null) {
  const start = formatTime(startTime);
  const end = formatTime(endTime);

  if (!start && !end) {
    return "-";
  }

  return `${start ?? "--:--"} - ${end ?? "--:--"}`;
}

function buildTripLogTableRow(log: DrivingLogLog): TripLogTableRow {
  const tripMode = log.tripMode ?? "DRIVE";
  const tripType = tripMode === "WALK" ? "walking" : tripMode === "RIDE" ? "ride" : "driving";
  const splitDisplay = getDrivingLogSplitDisplay({
    splitEnabled: tripMode !== "WALK" && log.vehicle?.enableBusinessSplit === true,
    businessKm: log.businessKm,
    personalKm: log.personalKm,
    totalKm: log.computedDistanceKm,
    tripType,
  });
  return {
    id: log.id,
    dateText: formatDate(log.date),
    timeText: formatTimeRange(log.startTime, log.endTime),
    tripModeText: tripMode,
    vehicleText: tripMode === "WALK" ? "-" : (log.vehicle?.name ?? "-"),
    journeyText: log.Tour?.title || "-",
    startLocationText: log.startLocation || "Unknown start",
    endLocationText: log.endLocation || "Unknown end",
    startOdometer: log.startOdometer,
    endOdometer: log.endOdometer,
    totalText: formatDistanceKm(log.computedDistanceKm, { tripType }),
    businessText: splitDisplay.primaryText,
    personalText: splitDisplay.secondaryText,
    splitText: splitDisplay.badgeText,
    showBusinessSplit: splitDisplay.showDetails,
    isAutoGenerated: isAutoGeneratedDrivingLog(log.notes),
  };
}

function isAutoGeneratedDrivingLog(notes?: string | null) {
  return (notes ?? "").includes("[Trip draft] Passive GPS session captured.");
}

function parsePageNumber(value?: string) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < 1) {
    return 1;
  }

  return Math.floor(parsed);
}

function parseDateStart(value?: string) {
  return parseAppDateStart(value);
}

function parseDateEnd(value?: string) {
  return parseAppDateEnd(value);
}

function buildPageHref(targetPage: number, searchParams: DrivingLogsSearchParams) {
  const params = new URLSearchParams();

  if (searchParams.from) {
    params.set("from", searchParams.from);
  }

  if (searchParams.to) {
    params.set("to", searchParams.to);
  }

  if (searchParams.journeyId) {
    params.set("journeyId", searchParams.journeyId);
  }

  if (searchParams.vehicleId) {
    params.set("vehicleId", searchParams.vehicleId);
  }

  if (searchParams.source) {
    params.set("source", searchParams.source);
  }

  if (searchParams.startLocation) {
    params.set("startLocation", searchParams.startLocation);
  }

  if (searchParams.endLocation) {
    params.set("endLocation", searchParams.endLocation);
  }

  if (searchParams.startOdometer) {
    params.set("startOdometer", searchParams.startOdometer);
  }

  if (targetPage > 1) {
    params.set("page", String(targetPage));
  }

  const query = params.toString();
  return query ? `/dashboard/logs/driving?${query}` : "/dashboard/logs/driving";
}

export default async function DrivingLogsPage({
  searchParams,
}: {
  searchParams: Promise<DrivingLogsSearchParams>;
}) {
  const resolvedSearchParams = await searchParams;
  const { from, to, journeyId, vehicleId, source, startLocation, endLocation, startOdometer, page } = resolvedSearchParams;
  const currentPage = parsePageNumber(page);
  const autoGeneratedOnly = source === "auto";
  const fromDate = parseDateStart(from);
  const toDate = parseDateEnd(to);
  const workspace = await requireCurrentWorkspace();

  const Tours = await listJourneys(workspace.id);
  const logsPage = await listDrivingLogsPage(workspace.id, currentPage, LOGS_PAGE_SIZE, {
    from: fromDate,
    to: toDate,
    journeyId,
    vehicleId,
    autoGeneratedOnly,
  });
  const vehicles = await listVehicles(workspace.id);

  const logs = logsPage.logs;
  const desktopRows = logs.map(buildTripLogTableRow);
  const totalPages = Math.max(1, Math.ceil(logsPage.totalCount / LOGS_PAGE_SIZE));
  const hasPreviousPage = currentPage > 1;
  const hasNextPage = currentPage < totalPages;

  const vehicleOdometerEntries: Array<readonly [string, number | null]> = [];
  for (const vehicle of vehicles) {
    vehicleOdometerEntries.push([
      vehicle.id,
      await getLatestOdometerForVehicle(workspace.id, vehicle.id),
    ]);
  }
  const vehicleOdometerMap = Object.fromEntries(vehicleOdometerEntries);
  const defaultVehicle = vehicles.find((vehicle) => vehicle.isDefault) ?? vehicles[0];
  const preferredJourneyIdFromQuery = journeyId && Tours.some((Tour) => Tour.id === journeyId) ? journeyId : undefined;
  const selectedVehicleId = vehicleId && vehicles.some((vehicle) => vehicle.id === vehicleId) ? vehicleId : "";
  const selectedJourneyFilterId = journeyId && Tours.some((Tour) => Tour.id === journeyId) ? journeyId : "";
  const hasFilters = Boolean(from || to || selectedVehicleId || selectedJourneyFilterId || autoGeneratedOnly);
  const preferredJourneyId =
    preferredJourneyIdFromQuery ?? Tours.find((Tour) => Tour.status === "ACTIVE")?.id ?? Tours[0]?.id ?? "";
  const prefilledStartOdometer =
    startOdometer && Number.isFinite(Number(startOdometer))
      ? Number(startOdometer)
      : (defaultVehicle ? (vehicleOdometerMap[defaultVehicle.id] ?? undefined) : undefined);

  return (
    <section className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">Trip logs</h1>
          <p className="text-muted-foreground">Track your route distance and keep each drive linked to your Tour timeline.</p>
        </div>
        <Link href="/dashboard/logs/driving/export" className={buttonVariants({ variant: "outline" })}>
          Export CSV
        </Link>
      </div>

      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <CardTitle>Recent trip entries</CardTitle>
              <p className="text-sm text-muted-foreground">
                Page {currentPage} of {totalPages} • {logsPage.totalCount} total entries
              </p>
            </div>
            {logsPage.totalCount > LOGS_PAGE_SIZE ? (
              <div className="flex items-center gap-2">
                <Link
                  href={buildPageHref(currentPage - 1, resolvedSearchParams)}
                  aria-disabled={!hasPreviousPage}
                  className={buttonVariants({
                    variant: "outline",
                    size: "sm",
                    className: !hasPreviousPage ? "pointer-events-none opacity-50" : undefined,
                  })}
                >
                  Previous
                </Link>
                <Link
                  href={buildPageHref(currentPage + 1, resolvedSearchParams)}
                  aria-disabled={!hasNextPage}
                  className={buttonVariants({
                    variant: "outline",
                    size: "sm",
                    className: !hasNextPage ? "pointer-events-none opacity-50" : undefined,
                  })}
                >
                  Next
                </Link>
              </div>
            ) : null}
          </div>
        </CardHeader>
        <CardContent>
          <form action="" method="GET" className="mb-5 grid gap-4 rounded-xl border border-border/70 bg-muted/15 p-4 md:grid-cols-2 xl:grid-cols-5">
            <div className="space-y-2">
              <Label htmlFor="filterFrom">From date</Label>
              <Input id="filterFrom" name="from" type="date" defaultValue={from ?? ""} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="filterTo">To date</Label>
              <Input id="filterTo" name="to" type="date" defaultValue={to ?? ""} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="filterVehicleId">Vehicle</Label>
              <select id="filterVehicleId" name="vehicleId" defaultValue={selectedVehicleId} className="w-full">
                <option value="">All vehicles</option>
                {vehicles.map((vehicle) => (
                  <option key={vehicle.id} value={vehicle.id}>
                    {vehicle.name}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="filterJourneyId">Tour</Label>
              <select id="filterJourneyId" name="journeyId" defaultValue={selectedJourneyFilterId} className="w-full">
                <option value="">All Tours</option>
                {Tours.map((Tour) => (
                  <option key={Tour.id} value={Tour.id}>
                    {Tour.title}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="filterSource">Source</Label>
              <select id="filterSource" name="source" defaultValue={autoGeneratedOnly ? "auto" : ""} className="w-full">
                <option value="">All entries</option>
                <option value="auto">Auto-generated only</option>
              </select>
            </div>
            <div className="flex flex-wrap items-end gap-2">
              <button type="submit" className={buttonVariants({ size: "sm" })}>
                Apply filters
              </button>
              {hasFilters ? (
                <Link href="/dashboard/logs/driving" className={buttonVariants({ variant: "ghost", size: "sm" })}>
                  Reset
                </Link>
              ) : null}
            </div>
          </form>

          {!logs.length ? (
            <EmptyState
              title={hasFilters ? "No trip logs match these filters" : "No driving logs yet"}
              description={hasFilters
                ? "Try clearing one or more filters to widen the results."
                : "No problem. Add your first trip and we will start tracking your distance automatically."}
              ctaLabel="Add first trip"
              ctaHref="#add-driving-log"
              secondaryCtaLabel="Go to Tours"
              secondaryCtaHref="/dashboard/Tours"
            />
          ) : (
            <>
              <div className="space-y-4 md:hidden">
                {logs.map((log) => {
                  const total = log.endOdometer - log.startOdometer;
                  return (
                    <article key={log.id} className="rounded-xl border border-border/70 bg-background/70 p-4 shadow-sm">
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <p className="font-medium text-foreground">{formatDate(log.date)}</p>
                          <p className="text-sm text-muted-foreground">{formatTimeRange(log.startTime, log.endTime)}</p>
                        </div>
                        {isAutoGeneratedDrivingLog(log.notes) ? <Badge variant="outline">Auto-generated</Badge> : null}
                      </div>

                      <div className="mt-4 grid gap-3 text-sm">
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Vehicle</p>
                          <p>{(log.tripMode ?? "DRIVE") === "WALK" ? "-" : (log.vehicle?.name ?? "-")}</p>
                        </div>
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Mode</p>
                          <p>{(log.tripMode ?? "DRIVE").toLowerCase()}</p>
                        </div>
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Tour</p>
                          <p>{log.Tour?.title || "-"}</p>
                        </div>
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Route</p>
                          <p>{log.startLocation || "Unknown start"}</p>
                          <p className="text-muted-foreground">to {log.endLocation || "Unknown end"}</p>
                        </div>
                        <div className="grid grid-cols-3 gap-3">
                          <div>
                            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Start</p>
                            <p>{(log.tripMode ?? "DRIVE") === "WALK" ? "-" : log.startOdometer}</p>
                          </div>
                          <div>
                            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">End</p>
                            <p>{(log.tripMode ?? "DRIVE") === "WALK" ? "-" : log.endOdometer}</p>
                          </div>
                          <div>
                            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Total</p>
                            <p className="font-medium">{formatDistanceKm(total, { tripType: (log.tripMode ?? "DRIVE") === "WALK" ? "walking" : (log.tripMode ?? "DRIVE") === "RIDE" ? "ride" : "driving" })}</p>
                          </div>
                        </div>
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Split</p>
                          <p>Business: {formatDistanceKm(log.businessKm, { tripType: (log.tripMode ?? "DRIVE") === "WALK" ? "walking" : (log.tripMode ?? "DRIVE") === "RIDE" ? "ride" : "driving" })}</p>
                          <p className="text-muted-foreground">Personal: {formatDistanceKm(log.personalKm, { tripType: (log.tripMode ?? "DRIVE") === "WALK" ? "walking" : (log.tripMode ?? "DRIVE") === "RIDE" ? "ride" : "driving" })}</p>
                        </div>
                      </div>

                      <div className="mt-4 flex flex-wrap gap-2">
                        <Link href={`/dashboard/logs/driving/${log.id}/edit`} className={buttonVariants({ variant: "outline", size: "sm" })}>
                          Edit
                        </Link>
                        <form action={deleteDrivingLogAction} id={`delete-driving-log-mobile-${log.id}`}>
                          <input type="hidden" name="logId" value={log.id} />
                          <ConfirmSubmitButton
                            formId={`delete-driving-log-mobile-${log.id}`}
                            triggerLabel="Delete"
                            title="Delete driving log?"
                            description="This driving log entry will be permanently removed."
                            confirmLabel="Delete"
                            size="sm"
                          />
                        </form>
                      </div>
                    </article>
                  );
                })}
              </div>

              <div className="hidden md:block">
                <ExpandableTripLogsTable key={desktopRows.map((row) => row.id).join("|")} rows={desktopRows} />
              </div>
            </>
          )}
        </CardContent>
      </Card>

      <Card id="add-driving-log">
        <CardHeader>
          <CardTitle>Add trip log</CardTitle>
        </CardHeader>
        <CardContent>
          <form action={createDrivingLogAction} className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="journeyId">Tour (optional)</Label>
              <select id="journeyId" name="journeyId" defaultValue={preferredJourneyId} className="w-full">
                <option value="">No Tour link</option>
                {Tours.map((Tour) => (
                  <option key={Tour.id} value={Tour.id}>
                    {Tour.title}
                  </option>
                ))}
              </select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="date">Date</Label>
              <Input id="date" name="date" type="date" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="startTime">Start time (optional)</Label>
              <Input id="startTime" name="startTime" type="time" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="endTime">End time (optional)</Label>
              <Input id="endTime" name="endTime" type="time" />
            </div>
            <AddressAutocompleteField
              label="Start location"
              name="startLocation"
              defaultValue={startLocation ?? ""}
              placeholder="Coburg VIC"
              helperText="Use suburb/state or a recognisable place name."
              formattedAddressName="startFormattedAddress"
              placeIdName="startPlaceId"
              latitudeName="startLatitude"
              longitudeName="startLongitude"
            />
            <AddressAutocompleteField
              label="End location"
              name="endLocation"
              defaultValue={endLocation ?? ""}
              placeholder="Brunswick VIC"
              helperText="Use suburb/state or a recognisable place name."
              formattedAddressName="endFormattedAddress"
              placeIdName="endPlaceId"
              latitudeName="endLatitude"
              longitudeName="endLongitude"
            />
            <VehicleOdometerFields
              vehicles={vehicles}
              vehicleOdometerMap={vehicleOdometerMap}
              defaultVehicleId={defaultVehicle?.id}
              initialStartOdometer={prefilledStartOdometer}
              initialBusinessKm={0}
              initialPersonalKm={0}
              initialTripMode="DRIVE"
              className="md:col-span-2"
            />
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="purpose">Purpose</Label>
              <Input id="purpose" name="purpose" placeholder="Client meeting" />
              <p className="text-xs text-muted-foreground">
                Examples: Client meeting, Travel between job sites, Personal errand, Fuel Gig.
              </p>
            </div>
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="notes">Notes</Label>
              <Textarea id="notes" name="notes" rows={3} />
            </div>
            <ActionSubmitButton label="Save log" pendingLabel="Saving..." className="md:col-span-2 md:w-fit" />
          </form>
        </CardContent>
      </Card>
    </section>
  );
}
